/* Transaction records from institution-exported CSV files; transaction_id is a synthetic key and account_id is caller-supplied */
CREATE TABLE IF NOT EXISTS raw.csv_transactions (
    transaction_id VARCHAR NOT NULL, -- Synthetic ID generated by the CSV extractor; not present in the source file; part of primary key
    account_id VARCHAR NOT NULL, -- Caller-supplied identifier; not present in the CSV file itself; part of primary key
    transaction_date DATE NOT NULL, -- Primary transaction date from the CSV; mapped to transaction_date in core
    post_date DATE, -- Settlement or posting date when present in CSV; mapped to authorized_date in core
    amount DECIMAL(18, 2) NOT NULL, -- Transaction amount; negative = expense, positive = income
    description VARCHAR, -- Merchant or payee description from the CSV; mapped to description in core
    memo VARCHAR, -- Supplemental transaction notes from the CSV; passed through to core
    category VARCHAR, -- Spending category pre-assigned by the institution in the CSV export
    subcategory VARCHAR, -- Spending subcategory pre-assigned by the institution in the CSV export
    transaction_type VARCHAR, -- Transaction type code from the CSV, e.g. DEBIT, CREDIT, CHECK; varies by institution
    transaction_status VARCHAR, -- Settlement status from the CSV, e.g. Posted, Pending; varies by institution
    check_number VARCHAR, -- Check number for paper check transactions; NULL for electronic transactions
    reference_number VARCHAR, -- Institution-assigned reference number; not propagated to core
    balance DECIMAL(18, 2), -- Running account balance after this transaction; not propagated to core
    member_name VARCHAR, -- Account holder name from credit union exports; not propagated to core
    source_file VARCHAR NOT NULL, -- Path to the CSV file this record was loaded from; part of primary key
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp when the CSV file was parsed
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp when this record was inserted into the database
    PRIMARY KEY (transaction_id, account_id, source_file)
);
