repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff
        language: system
        types: [python]
        args: [check, --fix]
        require_serial: false
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff
        language: system
        types: [python]
        args: [format]
        require_serial: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
