"""Execution-level E2E subprocess tests for the framework-generated report commands.

`testing.md`: every CLI command must have an E2E subprocess test. The ten
view-backed reports (`cash-flow`, `spending-trend`, `recurring-subscriptions`,
`merchant-activity`, `large-transactions`, `balance-drift`, `realized-fx`,
`net-worth`, `net-worth-currencies`, `net-worth-accounts`) are generated by
the report framework (`@report` runner → injected ``__signature__`` → Typer
command). Unit tests cover the generation logic against stub views in-process;
only a real subprocess invocation catches wiring bugs — the injected signature
conflicting with Typer's arg parsing, or a broken ``get_database`` path in the
generated callback.

The shared ``e2e_profile`` runs no transforms, so ``reports.*`` views don't
exist there. This module builds a profile whose encrypted DB carries minimal
stub ``reports.*`` views (one current-dated row each), then drives each command
as a subprocess and asserts a clean exit-0 JSON envelope. Read-only — the views
are installed once per module and shared.
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path

import pytest

from moneybin.database import Database
from tests.e2e.conftest import (
    TEST_ENCRYPTION_KEY,
    make_workflow_env,
    run_cli,
)


class _FixedKeyStore:
    """Minimal SecretStore stand-in returning the e2e encryption key."""

    def get_key(self, _name: str) -> str:
        return TEST_ENCRYPTION_KEY


pytestmark = pytest.mark.e2e

# One minimal row per view, with the exact columns each runner SELECTs. Dates are
# computed in-SQL via current_date so the time-windowed reports (cash-flow,
# spending-trend) return the row under their default last-12-months window — and so the
# DDL carries no Python interpolation (no S608 / SQL-injection surface).
_STUB_VIEWS = (
    """
    CREATE OR REPLACE VIEW reports.cash_flow AS SELECT * FROM (VALUES
        (strftime(current_date, '%Y-%m'), 'A1', 'Checking', 'Food', 'USD',
         100.0, -30.0, 70.0, 5)
    ) AS t(year_month, account_id, account_name, category, currency_code,
           inflow, outflow, net, txn_count)
    """,
    """
    CREATE OR REPLACE VIEW reports.spending_trend AS SELECT * FROM (VALUES
        (strftime(current_date, '%Y-%m'), 'Food', 'USD', -120.0, 8, -100.0,
         -20.0, 0.2, -110.0, -10.0, 0.09, -115.0)
    ) AS t(year_month, category, currency_code, total_spend, txn_count,
           prev_month_spend, mom_delta, mom_pct, prev_year_spend, yoy_delta,
           yoy_pct, trailing_3mo_avg)
    """,
    """
    CREATE OR REPLACE VIEW reports.recurring_subscriptions AS SELECT * FROM (VALUES
        ('m1', 'Netflix', 'USD', -15.99, 'monthly', 30.0, 1.5, 12,
         DATE '2025-01-01', DATE '2025-12-01', 'active', -191.88, 0.95)
    ) AS t(merchant_id, merchant_normalized, currency_code, avg_amount, cadence,
           interval_days_avg, interval_days_stddev, occurrence_count, first_seen,
           last_seen, status, annualized_cost, confidence)
    """,
    """
    CREATE OR REPLACE VIEW reports.merchant_activity AS SELECT * FROM (VALUES
        ('m1', 'Amazon', 'USD', -500.0, 0.0, -500.0, 12, -41.67, -38.0,
         DATE '2025-01-01', DATE '2025-12-01', 11, 'Shopping', 2)
    ) AS t(merchant_id, merchant_normalized, currency_code, total_spend,
           total_inflow, total_outflow, txn_count, avg_amount, median_amount,
           first_seen, last_seen, active_months, top_category, account_count)
    """,
    """
    CREATE OR REPLACE VIEW reports.large_transactions AS SELECT * FROM (VALUES
        ('t1', 'A1', 'Checking', current_date, -1200.0, 'Big purchase', 'm1',
         'Amazon', 'Shopping', 'USD', 3.1, 2.0, true)
    ) AS t(transaction_id, account_id, account_name, txn_date, amount,
           description, merchant_id, merchant_normalized, category,
           currency_code, amount_zscore_account, amount_zscore_category,
           is_top_100)
    """,
    """
    CREATE OR REPLACE VIEW reports.balance_drift AS SELECT * FROM (VALUES
        ('A1', 'Checking', 'USD', current_date, 1000.00, 1010.00, 10.00, 10.00,
         1.0, 5, 'drift')
    ) AS t(account_id, account_name, currency_code, assertion_date,
           asserted_balance, computed_balance, drift, drift_abs, drift_pct,
           days_since_assertion, status)
    """,
    """
    CREATE OR REPLACE VIEW reports.realized_fx AS SELECT * FROM (VALUES
        ('g1', 'c1', 'l1', 'A1', NULL, 't1', 't2', 's1', 's2', 'c0', NULL,
         NULL, 'Wallet', 'EUR', 'USD', 'EUR', 'USD', 'linked_two_row',
         'conversion', 'fifo', 'actual', 'manual', 'e2e', 'manual', 'e2e',
         'complete', NULL, current_date, current_date, current_date, 1.2, 1.2,
         current_timestamp, 45.0, 55.0, 45.0, 55.0, 50.0, 0.0, 5.0)
    ) AS t(realized_fx_gain_id, conversion_id, currency_lot_id, account_id,
           transfer_pair_id, from_transaction_id, to_transaction_id,
           from_source_transaction_id, to_source_transaction_id,
           source_conversion_id, source_investment_transaction_id,
           source_transfer_id, account_name, currency_code, home_currency,
           from_currency, to_currency, source_shape, acquisition_type,
           cost_basis_method, valuation_source_type, from_source_type,
           from_source_origin, to_source_type, to_source_origin, coverage_status,
           coverage_reason, acquisition_date, disposal_date, valuation_rate_date,
           executed_rate, valuation_rate, updated_at, from_amount, to_amount,
           disposed_amount, proceeds, cost_basis, fee_amount, gain_loss)
    """,
    """
    CREATE OR REPLACE VIEW reports.net_worth AS SELECT * FROM (VALUES
        ('USD', current_date, 3, 0, 1, 0, 0, 15000.00, -2500.00, 12500.00)
    ) AS t(home_currency_code, balance_date, account_count,
           carried_forward_count, currency_count, unpriced_currency_count,
           unanchored_account_count,
           total_assets, total_liabilities, net_worth)
    """,
    """
    CREATE OR REPLACE VIEW reports.net_worth_currencies AS SELECT * FROM (VALUES
        ('USD', 'USD', 'identity', current_date, current_date, 3, 0,
         15000.00, -2500.00, 12500.00, 15000.00, -2500.00, 12500.00)
    ) AS t(currency_code, home_currency_code, rate_source, balance_date,
           rate_published_date, account_count, carried_forward_count,
           total_assets, total_liabilities, net_worth, total_assets_home,
           total_liabilities_home, net_worth_home)
    """,
    """
    CREATE OR REPLACE VIEW reports.net_worth_accounts AS SELECT * FROM (VALUES
        ('A1', 'Checking', 'USD', 'USD', 'depository', true, 'ofx',
         'identity', current_date, current_date, 0, NULL, 5000.00, 5000.00)
    ) AS t(account_id, account_name, currency_code, home_currency_code,
           account_type, is_observed, observation_source, rate_source,
           balance_date, rate_published_date, days_since_observed,
           reconciliation_delta, account_balance, account_balance_home)
    """,
)


@pytest.fixture(scope="module")
def reports_env(e2e_home: Path) -> Iterator[dict[str, str]]:
    """A profile whose encrypted DB carries stub ``reports.*`` views.

    Opens the freshly-initialized profile DB in-process with the e2e key, installs
    the stub views, and closes before any subprocess runs (no concurrent file
    lock). Read-only commands share the result.
    """
    env = make_workflow_env(e2e_home, "e2e-reports")
    db_path = (
        Path(env["MONEYBIN_HOME"])
        / "profiles"
        / env["MONEYBIN_PROFILE"]
        / "moneybin.duckdb"
    )

    # Database caches the first key it resolves per process. Null it for this open
    # so the e2e key (not some prior unit test's key) is used; MonkeyPatch restores
    # the original on exit so we don't leak the e2e key into other tests.
    with pytest.MonkeyPatch.context() as mp:
        mp.setattr("moneybin.database._cached_encryption_key", None)
        db = Database(
            db_path,
            secret_store=_FixedKeyStore(),  # pyright: ignore[reportArgumentType]  # minimal SecretStore stand-in
            no_auto_upgrade=True,
            read_only=False,
        )
        try:
            db.execute("CREATE SCHEMA IF NOT EXISTS reports")
            for ddl in _STUB_VIEWS:
                db.execute(ddl)
        finally:
            db.close()

    yield env


@pytest.mark.parametrize(
    "command",
    [
        "cash-flow",
        "spending-trend",
        "recurring-subscriptions",
        "merchant-activity",
        "large-transactions",
        "balance-drift",
        "realized-fx",
        "net-worth",
        "net-worth-currencies",
        "net-worth-accounts",
    ],
)
def test_reports_command_runs_end_to_end(
    command: str, reports_env: dict[str, str]
) -> None:
    # Drives the generated command as a real subprocess: exercises Typer parsing
    # of the injected signature and the get_database path in the callback, which
    # the in-process unit tests cannot.
    result = run_cli("reports", command, "--output", "json", env=reports_env)
    result.assert_success()
    payload = json.loads(result.stdout)
    assert payload["status"] == "ok"
    assert isinstance(payload["data"], list)
