"""Shared names and defaults for database encryption."""

KEY_NAME = "DATABASE__ENCRYPTION_KEY"
SALT_NAME = "DATABASE__PASSPHRASE_SALT"

ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST = 65536
ARGON2_PARALLELISM = 4
ARGON2_HASH_LEN = 32
ENCRYPTION_KEY_BYTES = 32
PASSPHRASE_SALT_BYTES = 16
