"""Regenerate the generated reference pages under ``docs/reference/``.

Usage:
    uv run python scripts/generate_reference_docs.py [--check]

Writes ``docs/reference/cli/<command>.md`` and its ``README.md`` from the Typer
command tree, ``docs/reference/mcp-tools.md`` from the tool list the MCP server
hands a connecting client plus each registered tool's maximum sensitivity, and
``docs/reference/configuration.md`` from ``MoneyBinSettings``. ``--check``
exits non-zero when a checked-in page differs from the render; CI runs the
same comparison through
``tests/test_documentation_policy.py::test_generated_references_are_current``.
"""

from __future__ import annotations

import argparse
import asyncio
import enum
import inspect
import json
import re
import sys
import textwrap
import types
import typing
from collections.abc import Iterable, Mapping
from pathlib import Path

import click
from pydantic import BaseModel, SecretStr
from pydantic_core import PydanticUndefined
from pydantic_settings import BaseSettings
from rich.text import Text

from moneybin.mcp.surface import first_sentence

_REPO_ROOT = Path(__file__).resolve().parent.parent
_REFERENCE_DIR = _REPO_ROOT / "docs" / "reference"
_SCRIPT = "scripts/generate_reference_docs.py"

_MARKER = (
    "<!-- Generated by {script} from {source}. Do not edit; "
    "run `make generate-docs` after changing the source. -->"
)


def _marker(source: str) -> str:
    return _MARKER.format(script=_SCRIPT, source=source)


_CODE_SPAN_OR_ANGLE = re.compile(r"(`[^`]*`|\\<)|<")


def _escape_angles(text: str) -> str:
    """Escape ``<`` outside code spans: a bare ``<placeholder>`` is HTML to GitHub."""
    return _CODE_SPAN_OR_ANGLE.sub(lambda m: m.group(1) or "\\<", text)


def _cell(text: object) -> str:
    """Escape a table cell: pipes break the row, newlines break the table."""
    return _escape_angles(str(text).replace("|", "\\|").replace("\n", " ").strip())


def _code(text: object) -> str:
    return f"`{text}`"


def _table(headers: list[str], rows: Iterable[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines.extend("| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows)
    return lines


def _slug(heading: str) -> str:
    """GitHub's heading anchor: lower-case, spaces to hyphens, punctuation dropped."""
    text = re.sub(r"[^\w\- ]", "", heading.lower())
    return text.replace(" ", "-")


# --------------------------------------------------------------------------- CLI


def _plain(text: str) -> str:
    r"""Help text as ``--help`` shows it: the docstring cleaned, rich markup rendered.

    Typer's ``rich`` mode does the same, and rich drops click's ``\b`` marker
    with the other control codes.
    """
    return Text.from_markup(inspect.cleandoc(text)).plain


def _help_prose(text: str | None) -> str:
    """Return option or argument help as one paragraph."""
    return _escape_angles(_plain(text).strip()) if text else ""


_LIST_ITEM = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s")
_CONSOLE_LINE = re.compile(r"^(?:#|.*(?<![\w./:@-])moneybin\s)")
_CONTINUATION = re.compile(r"\\\n\s*")


def _fence(lines: list[str]) -> tuple[str, str]:
    """A verbatim block as ``(language, body)``; ``console`` when it is a transcript."""
    body = textwrap.dedent("\n".join(lines)).strip("\n")
    commands = _CONTINUATION.sub(" ", body).splitlines()
    shell = all(_CONSOLE_LINE.match(line) for line in commands if line.strip())
    return ("console" if shell else "text"), body


def _help_blocks(text: str | None) -> str:
    """Return a command's help as Markdown, keeping its verbatim blocks verbatim.

    Typer joins the first paragraph's lines and prints every later paragraph
    line by line, so an indented example or option table survives ``--help``
    but not Markdown, which fuses indented lines into the paragraph above. Such
    a paragraph keeps its non-indented lead as prose and renders the rest as a
    fenced block; indented list items stay prose, which Markdown renders as a
    list. A transcript fence is ``console``, so the docs guard checks it as it
    does every other fenced invocation.
    """
    if not text:
        return ""
    first, *rest = re.split(r"\n\s*\n", _plain(text).strip())
    blocks: list[str | tuple[str, str]] = [_escape_angles(first.replace("\n", " "))]
    for paragraph in rest:
        lines = paragraph.split("\n")
        split = next(
            (
                index
                for index, line in enumerate(lines)
                if line[:1].isspace() and not _LIST_ITEM.match(line)
            ),
            len(lines),
        )
        if split:
            blocks.append(_escape_angles("\n".join(lines[:split])))
        if split < len(lines):
            language, body = _fence(lines[split:])
            previous = blocks[-1]
            if isinstance(previous, tuple) and previous[0] == language:
                blocks[-1] = (language, previous[1] + "\n\n" + body)
            else:
                blocks.append((language, body))
    return "\n\n".join(
        block if isinstance(block, str) else f"```{block[0]}\n{block[1]}\n```"
        for block in blocks
    )


def _option_names(option: click.Option) -> str:
    names = ", ".join(option.opts)
    if option.secondary_opts:
        names += " / " + ", ".join(option.secondary_opts)
    return names


def _param_type(param: click.Parameter) -> str:
    kind = param.type
    if isinstance(param, click.Option) and param.is_flag:
        return "flag"
    if isinstance(param, click.Option) and param.count:
        return "count"
    if isinstance(kind, click.Choice):
        rendered = "one of " + ", ".join(_code(choice) for choice in kind.choices)
    elif isinstance(kind, (click.IntRange, click.FloatRange)):
        base = "int" if isinstance(kind, click.IntRange) else "float"
        bounds = []
        if kind.min is not None:
            bounds.append(f"≥ {kind.min}")
        if kind.max is not None:
            bounds.append(f"≤ {kind.max}")
        rendered = base + (f" ({', '.join(bounds)})" if bounds else "")
    else:
        rendered = {
            "text": "text",
            "integer": "int",
            "float": "float",
            "boolean": "bool",
            "path": "path",
            "file": "file",
            "datetime": "datetime",
            "uuid": "uuid",
        }.get(kind.name, kind.name)
    if param.nargs not in (1, None) or getattr(param, "multiple", False):
        rendered += ", repeatable"
    return rendered


_CLICK_UNSET = getattr(click.core, "UNSET", None)  # click 8.3's "no default" sentinel


def _render_default(value: object) -> str:
    if value is None or value is PydanticUndefined or value is _CLICK_UNSET:
        return ""
    if isinstance(value, enum.Enum):
        value = value.value
    if isinstance(value, bool):
        return _code(str(value).lower())
    if isinstance(value, (list, tuple)):
        return ", ".join(_render_default(item) for item in value) if value else ""
    if isinstance(value, Path):
        return _code(value)
    if isinstance(value, str):
        return _code(value) if value else '`""`'
    return _code(value)


def _option_default(option: click.Option, ctx: click.Context) -> str:
    bare_flag = option.is_flag and not option.secondary_opts
    if bare_flag or option.show_default is False:
        return ""
    if isinstance(option.show_default, str):
        return option.show_default
    return _render_default(option.get_default(ctx, call=True))


def _option_description(option: click.Option) -> str:
    """The option's help, prefixed when required and suffixed with its env var."""
    parts = ["Required." if option.required else "", _help_prose(option.help)]
    envvar = option.envvar
    if envvar:
        names = [envvar] if isinstance(envvar, str) else list(envvar)
        parts.append("Env: " + ", ".join(_code(name) for name in names) + ".")
    return " ".join(part for part in parts if part)


def _option_rows(
    options: Iterable[click.Option], ctx: click.Context
) -> list[list[str]]:
    return [
        [
            _code(_option_names(option)),
            _param_type(option),
            _option_default(option, ctx),
            _option_description(option),
        ]
        for option in options
    ]


def _walk(
    command: click.Command, ctx: click.Context
) -> list[tuple[click.Command, click.Context]]:
    """Depth-first (command, context) pairs below ``command``, skipping hidden ones."""
    found: list[tuple[click.Command, click.Context]] = []
    if not isinstance(command, click.Group):
        return found
    for name in command.list_commands(ctx):
        child = command.get_command(ctx, name)
        if child is None or child.hidden:
            continue
        child_ctx = click.Context(child, info_name=name, parent=ctx)
        found.append((child, child_ctx))
        found.extend(_walk(child, child_ctx))
    return found


def _command_section(
    command: click.Command, ctx: click.Context, level: int = 2, intro: str = ""
) -> list[str]:
    path = ctx.command_path
    lines = [f"{'#' * level} {path}", ""]
    if command.deprecated:
        lines += ["**Deprecated.**", ""]
    help_text = _help_blocks(command.help)
    if help_text:
        lines += [help_text, ""]
    if intro:
        lines += [intro, ""]
    # A synopsis names the command's shape; it is not a transcript, so it is
    # an inline span (the docs guard holds fenced blocks to "runs as written").
    usage = " ".join([path, *command.collect_usage_pieces(ctx)])
    lines += [f"Usage: `{usage}`", ""]
    if isinstance(command, click.Group):
        rows = []
        for name in command.list_commands(ctx):
            child = command.get_command(ctx, name)
            if child is None or child.hidden:
                continue
            child_path = f"{path} {name}"
            rows.append([
                f"[{_code(child_path)}](#{_slug(child_path)})",
                child.get_short_help_str(limit=200),
            ])
        if rows:
            lines += ["**Commands**", ""]
            lines += _table(["Command", "Purpose"], rows)
            lines.append("")
    # Typer arguments carry ``hidden``; plain click arguments do not.
    arguments = [
        p
        for p in command.params
        if isinstance(p, click.Argument) and not getattr(p, "hidden", False)
    ]
    if arguments:
        rows = [
            [
                _code(argument.make_metavar(ctx)),
                _param_type(argument),
                "yes" if argument.required else "no",
                _help_prose(getattr(argument, "help", None)),
            ]
            for argument in arguments
        ]
        lines += ["**Arguments**", ""]
        lines += _table(["Argument", "Type", "Required", "Description"], rows)
        lines.append("")
    options = [
        p for p in command.params if isinstance(p, click.Option) and not p.hidden
    ]
    if options:
        lines += ["**Options**", ""]
        lines += _table(
            ["Option", "Type", "Default", "Description"], _option_rows(options, ctx)
        )
        lines.append("")
    return lines


_PAGE_INTRO = (
    "Generated from the registered command tree, so every option below is one "
    "the command declares; `--help` on any command prints the same text. "
    "Shared flags, exit codes, and JSON envelopes: "
    "[CLI reference](../../guides/cli-reference.md)."
)


def render_cli_pages(root: click.Group) -> dict[str, str]:
    """Return ``{relative path: text}`` for the CLI reference directory."""
    root_ctx = click.Context(root, info_name="moneybin")
    pages: dict[str, str] = {}
    index_rows: list[list[str]] = []
    for name in root.list_commands(root_ctx):
        command = root.get_command(root_ctx, name)
        if command is None or command.hidden:
            continue
        ctx = click.Context(command, info_name=name, parent=root_ctx)
        summary = command.get_short_help_str(limit=200)
        index_rows.append([f"[{_code('moneybin ' + name)}]({name}.md)", summary])
        lines = [_marker("the Typer command tree")]
        lines += _command_section(command, ctx, level=1, intro=_PAGE_INTRO)
        for child, child_ctx in _walk(command, ctx):
            lines += _command_section(child, child_ctx)
        pages[f"{name}.md"] = "\n".join(lines).rstrip() + "\n"

    root_options = [
        p for p in root.params if isinstance(p, click.Option) and not p.hidden
    ]
    index = [
        _marker("the Typer command tree"),
        "# CLI command tree",
        "",
        "One page per top-level command, generated from the registered command "
        "tree. Hidden commands are omitted, as they are from `--help`. For the "
        "conventions every command shares (standard flags, exit codes, output "
        "envelopes, date formats) read the hand-written "
        "[CLI reference](../../guides/cli-reference.md).",
        "",
        "Usage: `" + " ".join(["moneybin", *root.collect_usage_pieces(root_ctx)]) + "`",
        "",
        "**Global options**",
        "",
        *_table(
            ["Option", "Type", "Default", "Description"],
            _option_rows(root_options, root_ctx),
        ),
        "",
        "**Commands**",
        "",
        *_table(["Command", "Purpose"], index_rows),
    ]
    pages["README.md"] = "\n".join(index).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------- MCP


def _json_code(value: object) -> str:
    """A JSON value as a code span: strings bare, everything else JSON-encoded."""
    return _code(value if isinstance(value, str) else json.dumps(value))


def _oneof_variant_name(variant: Mapping[str, object], index: int) -> str:
    """Name a discriminated-union variant: its discriminator's const, else its title."""
    for prop_schema in typing.cast(
        Mapping[str, Mapping[str, object]], variant.get("properties", {})
    ).values():
        if "const" in prop_schema:
            return str(prop_schema["const"])
    title = variant.get("title")
    return str(title) if title else f"variant {index + 1}"


def _oneof_variants(schema: Mapping[str, object]) -> list[Mapping[str, object]] | None:
    """The ``oneOf`` variants on this schema, under its nullable wrapper, or on its items.

    Mirrors the unwrapping in ``_schema_type`` so an optional discriminated
    union gets the same variants block as a required one. An ``anyOf`` with
    more than one non-null option is a real alternation, not a wrapper, and
    yields no block.
    """
    if "oneOf" in schema:
        return typing.cast(list[Mapping[str, object]], schema["oneOf"])
    if "anyOf" in schema:
        options = [
            option
            for option in typing.cast(list[Mapping[str, object]], schema["anyOf"])
            if option.get("type") != "null"
        ]
        return _oneof_variants(options[0]) if len(options) == 1 else None
    if schema.get("type") == "array":
        return _oneof_variants(
            typing.cast(Mapping[str, object], schema.get("items", {}))
        )
    return None


def _schema_type(schema: Mapping[str, object]) -> str:
    if "const" in schema:
        return _json_code(schema["const"])
    if "enum" in schema:
        values = typing.cast(list[object], schema["enum"])
        return "one of " + ", ".join(_json_code(value) for value in values)
    if "oneOf" in schema:
        options = typing.cast(list[Mapping[str, object]], schema["oneOf"])
        names = [
            _oneof_variant_name(option, index) for index, option in enumerate(options)
        ]
        return "one of " + ", ".join(_code(name) for name in names)
    if "anyOf" in schema:
        options = typing.cast(list[Mapping[str, object]], schema["anyOf"])
        parts = [
            _schema_type(option) for option in options if option.get("type") != "null"
        ]
        return " or ".join(dict.fromkeys(parts)) or "any"
    kind = schema.get("type")
    if kind == "array":
        items = typing.cast(Mapping[str, object], schema.get("items", {}))
        return f"array of {_schema_type(items)}"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, Mapping):
            return f"object of {_schema_type(typing.cast(Mapping[str, object], extra))}"
        return "object"
    if isinstance(kind, list):
        return " or ".join(str(part) for part in kind if part != "null")
    return str(kind) if kind else "any"


_CONSTRAINT_KEYS = (
    ("minimum", "≥ {}"),
    ("exclusiveMinimum", "> {}"),
    ("maximum", "≤ {}"),
    ("exclusiveMaximum", "< {}"),
    ("minLength", "min length {}"),
    ("maxLength", "max length {}"),
    ("minItems", "min items {}"),
    ("maxItems", "max items {}"),
    ("pattern", "pattern `{}`"),
    ("format", "format {}"),
)


def _schema_notes(name: str, schema: Mapping[str, object], required: set[str]) -> str:
    notes = ["required"] if name in required else []
    for key, template in _CONSTRAINT_KEYS:
        if key in schema:
            notes.append(template.format(schema[key]))
    if "anyOf" in schema:
        options = typing.cast(list[Mapping[str, object]], schema["anyOf"])
        for option in options:
            if option.get("type") == "null":
                continue
            for key, template in _CONSTRAINT_KEYS:
                if key in option:
                    notes.append(template.format(option[key]))
    if "description" in schema:
        notes.append(str(schema["description"]))
    return "; ".join(notes)


def _schema_default(schema: Mapping[str, object]) -> str:
    if schema.get("default") is None:
        return ""
    return _json_code(schema["default"])


def _property_rows(
    properties: Mapping[str, Mapping[str, object]], required: set[str]
) -> list[list[str]]:
    return [
        [
            _code(name),
            _schema_type(schema),
            _schema_default(schema),
            _schema_notes(name, schema, required),
        ]
        for name, schema in properties.items()
    ]


def _variant_sections(
    param_name: str, variants: list[Mapping[str, object]]
) -> list[str]:
    """A ``Variants of `param_name`` block: one field table per discriminated variant."""
    lines = [f"#### Variants of {_code(param_name)}", ""]
    for index, variant in enumerate(variants):
        lines += [f"##### {_code(_oneof_variant_name(variant, index))}", ""]
        description = variant.get("description")
        if description:
            lines += [_escape_angles(str(description).strip()), ""]
        properties = typing.cast(
            Mapping[str, Mapping[str, object]], variant.get("properties", {})
        )
        required = set(typing.cast(list[str], variant.get("required", [])))
        if properties:
            lines += _table(
                ["Field", "Type", "Default", "Notes"],
                _property_rows(properties, required),
            )
        lines.append("")
    return lines[:-1]


def _access(annotations: Mapping[str, object]) -> str:
    parts = ["read-only" if annotations.get("readOnlyHint") else "write"]
    if annotations.get("destructiveHint"):
        parts.append("destructive")
    parts.append(
        "idempotent" if annotations.get("idempotentHint") else "not idempotent"
    )
    if annotations.get("openWorldHint"):
        parts.append("open world")
    return ", ".join(parts)


def render_mcp_tools(
    surface: Mapping[str, object], sensitivities: Mapping[str, str]
) -> str:
    """Render the MCP tool reference from the client-visible surface and runtime tiers."""
    tools = sorted(
        typing.cast(list[Mapping[str, object]], surface["tools"]),
        key=lambda tool: str(tool["name"]),
    )
    missing = [
        str(tool["name"]) for tool in tools if str(tool["name"]) not in sensitivities
    ]
    if missing:
        raise ValueError(f"no registered sensitivity for listed tools: {missing}")
    count = int(typing.cast(int, surface["tool_count"]))
    lines = [
        _marker(
            "the tool list the MCP server hands a connecting client, plus the "
            "registered tool metadata"
        ),
        "# MCP tool reference",
        "",
        f"The standard registry exposes {count} tools. Each entry below is the "
        "tool's client-visible definition — its description, parameters, and "
        "MCP annotations — plus the maximum sensitivity the server derives from "
        "its typed response. Every tool returns the response envelope described "
        "in [`architecture.md`](../architecture.md): `status`, `summary`, "
        "`data`, `actions`, with `error` on failure and `next_cursor` when more "
        "rows remain. How the server is installed and driven: "
        "[MCP server](../guides/mcp-server.md).",
        "",
        "## Tools",
        "",
    ]
    summary_rows = []
    for tool in tools:
        name = str(tool["name"])
        definition = typing.cast(Mapping[str, object], tool["definition"])
        annotations = typing.cast(
            Mapping[str, object], definition.get("annotations", {})
        )
        summary_rows.append([
            f"[{_code(name)}](#{_slug(name)})",
            first_sentence(str(definition.get("description", "")).strip()),
            _access(annotations),
            _code(sensitivities[name]),
        ])
    lines += _table(["Tool", "Purpose", "Access", "Max sensitivity"], summary_rows)
    lines.append("")
    for tool in tools:
        name = str(tool["name"])
        definition = typing.cast(Mapping[str, object], tool["definition"])
        annotations = typing.cast(
            Mapping[str, object], definition.get("annotations", {})
        )
        schema = typing.cast(Mapping[str, object], definition.get("inputSchema", {}))
        properties = typing.cast(
            Mapping[str, Mapping[str, object]], schema.get("properties", {})
        )
        required = set(typing.cast(list[str], schema.get("required", [])))
        lines += [f"### {name}", ""]
        lines += [_escape_angles(str(definition.get("description", "")).strip()), ""]
        lines += [
            f"Access: {_access(annotations)}. Maximum sensitivity: "
            f"{_code(sensitivities[name])}.",
            "",
        ]
        if properties:
            lines += _table(
                ["Parameter", "Type", "Default", "Notes"],
                _property_rows(properties, required),
            )
            for prop_name, prop_schema in properties.items():
                variants = _oneof_variants(prop_schema)
                if variants:
                    lines.append("")
                    lines += _variant_sections(prop_name, variants)
        else:
            lines.append("No parameters.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def live_mcp_surface() -> tuple[dict[str, object], dict[str, str]]:
    """The tool list a connecting client receives, and each tool's maximum sensitivity.

    One in-process boot of the standard registry serves both: the client list
    is what ``moneybin mcp serve`` would hand a client (the same inventory
    ``tests/fixtures/mcp_surface/standard.json`` freezes), and the tiers come
    from the registered functions behind it. No database is opened.
    """
    from fastmcp import Client

    from moneybin.mcp.server import mcp, register_core_tools
    from moneybin.mcp.surface_inventory import SurfaceInventory

    register_core_tools()

    async def inventory() -> dict[str, object]:
        async with Client(mcp) as client:
            return SurfaceInventory.from_tools(await client.list_tools()).to_dict()

    surface = asyncio.run(inventory())
    sensitivities: dict[str, str] = {}
    for tool in asyncio.run(mcp.list_tools(run_middleware=False)):
        fn = getattr(tool, "fn", None)
        sensitivity = getattr(fn, "_mcp_maximum_sensitivity", None)
        if sensitivity is None:
            raise ValueError(f"tool {tool.name} carries no _mcp_maximum_sensitivity")
        sensitivities[tool.name] = str(getattr(sensitivity, "value", sensitivity))
    return surface, sensitivities


# ----------------------------------------------------------------- configuration


def _submodel(annotation: object) -> type[BaseModel] | None:
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    origin = typing.get_origin(annotation)
    if origin is typing.Union or origin is types.UnionType:
        for arg in typing.get_args(annotation):
            if isinstance(arg, type) and issubclass(arg, BaseModel):
                return arg
    return None


def _annotation_text(annotation: object) -> str:
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if annotation is SecretStr:
        return "secret"
    if origin is typing.Literal:
        return "one of " + ", ".join(_json_code(arg) for arg in args)
    if origin is typing.Union or origin is types.UnionType:
        parts = [_annotation_text(arg) for arg in args if arg is not type(None)]
        optional = any(arg is type(None) for arg in args)
        return " or ".join(parts) + (" (optional)" if optional else "")
    if origin in (list, tuple, set, frozenset):
        inner = ", ".join(_annotation_text(arg) for arg in args if arg is not Ellipsis)
        return f"list of {inner}" if inner else "list"
    if origin is dict:
        key, value = (_annotation_text(arg) for arg in args) if args else ("any", "any")
        return f"mapping of {key} to {value}"
    if isinstance(annotation, type):
        if issubclass(annotation, enum.Enum):
            return "one of " + ", ".join(_code(member.value) for member in annotation)
        return {"str": "text", "int": "int", "float": "float", "bool": "bool"}.get(
            annotation.__name__, annotation.__name__
        )
    return str(annotation)


def _constraints(metadata: Iterable[object]) -> list[str]:
    notes: list[str] = []
    for item in metadata:
        for attribute, template in (
            ("ge", "≥ {}"),
            ("gt", "> {}"),
            ("le", "≤ {}"),
            ("lt", "< {}"),
            ("min_length", "min length {}"),
            ("max_length", "max length {}"),
        ):
            value = getattr(item, attribute, None)
            if value is not None:
                notes.append(template.format(value))
    return notes


def _settings_default(field: typing.Any, env: str) -> str:
    if env in _PROFILE_DERIVED_DEFAULTS:
        return _PROFILE_DERIVED_DEFAULTS[env]
    if field.default_factory is not None:
        value = field.default_factory()
    else:
        value = field.default
    if value is PydanticUndefined:
        return "required"
    if isinstance(value, SecretStr):
        return "built in" if value.get_secret_value() else "unset"
    if isinstance(value, Path):
        home = Path.home()
        try:
            value = Path("~") / value.relative_to(home)
        except ValueError:
            pass
        return _code(value)
    if value is None:
        return "unset"
    if isinstance(value, dict):
        return _code(json.dumps(value, sort_keys=True))
    return _render_default(value)


_PROFILE_DERIVED_DEFAULTS = {
    "MONEYBIN_DATABASE__PATH": "`<profile dir>/moneybin.duckdb`",
    "MONEYBIN_DATABASE__BACKUP_PATH": "`<profile dir>/backups`",
    "MONEYBIN_DATABASE__TEMP_DIRECTORY": "`<profile dir>/temp`",
    "MONEYBIN_DATA__RAW_DATA_PATH": "`<profile dir>/raw`",
    "MONEYBIN_DATA__TEMP_DATA_PATH": "`<profile dir>/temp`",
    "MONEYBIN_LOGGING__LOG_FILE_PATH": "`<profile dir>/logs/moneybin.log`",
}


def _field_row(
    model: type[BaseModel], prefix: list[str], name: str, field: typing.Any
) -> list[str]:
    # pydantic-settings resolves nested env names from field names, not
    # aliases: the `import_` section reads MONEYBIN_IMPORT___* (three
    # underscores), which `MoneyBinSettings.import_` documents.
    env = "MONEYBIN_" + "__".join(part.upper() for part in [*prefix, name])
    if not field.description:
        raise ValueError(f"{model.__name__}.{name} ({env}) has no description")
    notes = _constraints(field.metadata)
    type_text = _annotation_text(field.annotation)
    if notes:
        type_text += " (" + ", ".join(notes) + ")"
    return [_code(env), type_text, _settings_default(field, env), field.description]


def _settings_rows(model: type[BaseModel], prefix: list[str]) -> list[list[str]]:
    rows: list[list[str]] = []
    for name, field in model.model_fields.items():
        sub = _submodel(field.annotation)
        if sub is not None:
            rows.extend(_settings_rows(sub, [*prefix, name]))
        else:
            rows.append(_field_row(model, prefix, name, field))
    return rows


#: Sections `MoneyBinSettings.__init__` passes whole from the active profile.
#: A constructor value is the highest-precedence source, so nothing in these
#: sections can be set from the environment or the dotenv file.
_PROFILE_BOUND_SECTIONS = {"database", "data", "logging"}
_PROFILE_BOUND_NOTE = (
    "`MoneyBinSettings` builds this whole section from the active profile's "
    "directory when it is constructed, and a constructor value outranks the "
    "environment and the dotenv file, so the variables below are not read "
    "today: every profile runs on the defaults shown."
)


def render_configuration(settings_cls: type[BaseSettings]) -> str:
    """Render the configuration reference from the settings model."""
    config = settings_cls.model_config
    prefix = str(config.get("env_prefix", ""))
    delimiter = str(config.get("env_nested_delimiter", "__"))
    lines = [
        _marker("`MoneyBinSettings` in `src/moneybin/config.py`"),
        "# Configuration reference",
        "",
        "Every setting MoneyBin reads, one row per value. Set a value as an "
        f"environment variable with the `{prefix}` prefix, joining nested "
        f"sections with `{delimiter}` (`{prefix}MCP{delimiter}MAX_ROWS`), or "
        "put the same lines in `.env.<profile>` under the data home, falling "
        "back to `.env`. Precedence is explicit constructor values, then the "
        "process environment, then the dotenv file. `MONEYBIN_HOME` itself "
        "must come from the environment or `--home`: the dotenv file lives "
        "inside the home it would name.",
        "",
        "Paths marked `<profile dir>` resolve to `<home>/profiles/<profile>/`.",
        "",
    ]
    sections: list[tuple[str, str, type[BaseModel], str]] = []
    for name, field in settings_cls.model_fields.items():
        sub = _submodel(field.annotation)
        if sub is not None:
            summary = field.description or (sub.__doc__ or "").strip().split("\n")[0]
            sections.append((field.alias or name, name, sub, summary))
    top_rows = [
        _field_row(settings_cls, [], name, field)
        for name, field in settings_cls.model_fields.items()
        if _submodel(field.annotation) is None
    ]
    if top_rows:
        lines += ["## Top level", ""]
        lines += _table(["Variable", "Type", "Default", "Description"], top_rows)
        lines.append("")
    for key, field_name, model, description in sections:
        lines += [f"## {key}", ""]
        if description:
            lines += [description, ""]
        if field_name in _PROFILE_BOUND_SECTIONS:
            lines += [_PROFILE_BOUND_NOTE, ""]
        lines += _table(
            ["Variable", "Type", "Default", "Description"],
            _settings_rows(model, [field_name]),
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ------------------------------------------------------------------------ driver


def generated_pages() -> dict[Path, str]:
    """Every generated page, keyed by path relative to ``docs/reference/``."""
    from typer.main import get_command

    from moneybin.cli.main import app
    from moneybin.config import MoneyBinSettings

    root = get_command(app)
    if not isinstance(root, click.Group):
        raise TypeError("the moneybin root command is not a click.Group")
    pages = {Path("cli") / name: text for name, text in render_cli_pages(root).items()}
    pages[Path("mcp-tools.md")] = render_mcp_tools(*live_mcp_surface())
    pages[Path("configuration.md")] = render_configuration(MoneyBinSettings)
    return pages


def _orphaned_cli_pages(reference_dir: Path, pages: Mapping[Path, str]) -> list[Path]:
    """Generated CLI pages on disk whose command the tree no longer renders."""
    cli_dir = reference_dir / "cli"
    marker = _marker("the Typer command tree")
    return [
        existing.relative_to(reference_dir)
        for existing in (sorted(cli_dir.glob("*.md")) if cli_dir.exists() else [])
        if existing.relative_to(reference_dir) not in pages
        and existing.read_text().startswith(marker)
    ]


def stale_pages(reference_dir: Path = _REFERENCE_DIR) -> list[Path]:
    """Generated paths whose checked-in text differs, is missing, or is orphaned."""
    pages = generated_pages()
    stale = [
        path
        for path, text in pages.items()
        if not (reference_dir / path).exists()
        or (reference_dir / path).read_text() != text
    ]
    return stale + _orphaned_cli_pages(reference_dir, pages)


def write_pages(reference_dir: Path = _REFERENCE_DIR) -> list[Path]:
    """Write every page; drop generated CLI pages whose command no longer exists."""
    pages = generated_pages()
    written: list[Path] = []
    for path, text in pages.items():
        target = reference_dir / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text() != text:
            target.write_text(text)
            written.append(path)
    for orphan in _orphaned_cli_pages(reference_dir, pages):
        (reference_dir / orphan).unlink()
        written.append(orphan)
    return written


def main(argv: list[str] | None = None) -> int:
    """Write the pages, or with ``--check`` report which ones are stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--reference-dir", type=Path, default=_REFERENCE_DIR)
    args = parser.parse_args(argv)
    reference_dir: Path = args.reference_dir
    if reference_dir.resolve().is_relative_to(_REPO_ROOT):
        reference_dir = reference_dir.resolve().relative_to(_REPO_ROOT)
    if args.check:
        stale = stale_pages(args.reference_dir)
        for path in stale:
            print(f"stale: {reference_dir / path}")  # noqa: T201  # script output
        return 1 if stale else 0
    for path in write_pages(args.reference_dir):
        print(f"wrote {reference_dir / path}")  # noqa: T201  # script output
    return 0


if __name__ == "__main__":
    sys.exit(main())
