"""Committed statement PDFs, copied into a test's tmp_path.

The card and checking statements are a matched pair: same issuer, same columns,
same balances, same two amounts — differing ONLY in the credit-card disclosures.
That isolates what the disclosures alone change, which is the whole subject of
the sign-convention gate: the numbers reconcile either way, so nothing but the
disclosures can tell a +150 charge from a +150 paycheck.

Generated by ``test_extractors/test_pdf/_make_fixture.py`` (reportlab is a
one-shot generator dep, never a test dep — the PDFs are committed). Copied into
``tmp_path`` rather than imported in place so each import gets its own
``source_file`` and no test writes near the repo fixtures.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

_FIXTURES = Path(__file__).parent / "test_extractors" / "test_pdf" / "fixtures"


def _copy(name: str, tmp_path: Path) -> Path:
    src = _FIXTURES / f"{name}.pdf"
    if not src.exists():
        pytest.skip(f"fixture missing: {src} (run _make_fixture.py)")
    dest = tmp_path / f"{name}.pdf"
    shutil.copy(src, dest)
    return dest


def write_card_statement_pdf(tmp_path: Path, *, month: str = "01") -> Path:
    """A Chase credit-card statement: +150.00 charge, -50.00 payment.

    Carries ``Minimum Payment Due`` and ``Credit Limit``; opening 0.00, closing
    100.00 (the printed amounts reconcile: 150.00 - 50.00 = 100.00). ``month``
    selects a second statement in the identical layout — same fingerprint, so it
    replays the saved recipe.
    """
    return _copy(f"chase_card_2024_{month}", tmp_path)


def write_checking_statement_pdf(tmp_path: Path) -> Path:
    """The card statement's twin with no card disclosures: -50.00 debit, +150.00 credit."""
    return _copy("chase_checking_2024_01", tmp_path)
