"""Categorization writes: per-transaction edits, taxonomy, rules, exemplars.

Every write to ``app.transaction_categories``, ``app.user_merchants``,
``app.user_categories``, ``app.category_overrides``, and
``app.categorization_rules`` routes through this module. Pairs with
``CategorizationMatcher`` (read-only) under the facade.

Audit emission is scoped to the user-manual-edit path
(``set_category`` / ``clear_category``). Bulk and automated writes are
deliberately audit-silent today; broader coverage is tracked in the
app-integrity Invariant 10 work and intentionally out of scope here.

Source-precedence enforcement is centralised in :meth:`write_categorization`:
every write compares the incoming source's priority (from
``_shared.SOURCE_PRIORITY``) against the existing row's via the same
SQL CASE expression generated by ``_shared.priority_case_sql``, so the
ladder lives in exactly one place. The lone sanctioned bypass is
:meth:`set_category_in_active_txn`, which is restricted to
``categorized_by='user'`` precisely so admitting a lower-priority source
through it would be impossible. The two methods co-locate here so the
warning in the bypass's docstring stays next to the guard it bypasses.
"""

from __future__ import annotations

import logging
from collections.abc import Generator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Literal, cast

import duckdb

from moneybin.database import Database
from moneybin.errors import UserError
from moneybin.metrics.registry import (
    CATEGORIZE_WRITE_SKIPPED_PRECEDENCE_TOTAL,
    MERCHANT_EXEMPLAR_COUNT,
)
from moneybin.privacy.payloads.categorize import RulesCreatePayload
from moneybin.repositories.categorization_rules_repo import CategorizationRulesRepo
from moneybin.repositories.transaction_categories_repo import (
    TransactionCategoriesRepo,
)
from moneybin.repositories.user_categories_repo import (
    CategoryOverridesRepo,
    UserCategoriesRepo,
)
from moneybin.repositories.user_merchants_repo import UserMerchantsRepo
from moneybin.services.audit_service import AuditService
from moneybin.services.categorization._shared import (
    SOURCE_PRIORITY,
    CategorizationRuleInput,
    InternalMatchType,
    resolve_category_id,
)
from moneybin.tables import (
    BUDGETS,
    CATEGORIES,
    CATEGORIZATION_RULES,
    CATEGORY_SOURCE_MAP,
    PROPOSED_RULES,
    TRANSACTION_CATEGORIES,
    TRANSACTION_SPLITS,
    USER_CATEGORIES,
    USER_MERCHANTS,
)

logger = logging.getLogger(__name__)


@dataclass(slots=True, frozen=True)
class WriteOutcome:
    """Result of a guarded write to ``app.transaction_categories``.

    Returned by :meth:`MatchApplier.write_categorization`. The ``written``
    flag distinguishes successful writes (insert or precedence-permitted
    update) from precedence-blocked attempts. ``skipped_reason`` is
    populated only when ``written`` is False.
    """

    written: bool
    skipped_reason: Literal["lower_priority_source"] | None = None


@dataclass(slots=True)
class RuleCreationResult:
    """Typed result for ``MatchApplier.create_rules_core``."""

    created: int
    existing: int
    skipped: int
    error_details: list[dict[str, str]]
    rule_ids: list[str]

    def to_payload(self) -> RulesCreatePayload:
        """Return a typed payload for the MCP/CLI envelope boundary."""
        return RulesCreatePayload(
            created=self.created,
            existing=self.existing,
            skipped=self.skipped,
            rule_ids=list(self.rule_ids),
            error_details=list(self.error_details),
        )

    def merge_parse_errors(self, parse_errors: list[dict[str, str]]) -> None:
        """Prepend boundary-validation errors and reflect them in the skipped count."""
        if not parse_errors:
            return
        self.error_details = parse_errors + self.error_details
        self.skipped += len(parse_errors)


class MatchApplier:
    """All writes to ``app.*`` categorization tables.

    Holds a ``Database`` handle plus an injected ``AuditService`` so the
    user-manual-edit path can emit ``category.set`` / ``category.clear``
    events alongside the underlying mutation.

    The ``*_core`` methods (``create_merchant_core``, ``create_rules_core``,
    ``deactivate_rule_core``) deliberately omit the optional ``reapply``
    semantics: the facade pairs the write with ``categorize_pending`` when
    callers ask for it. Splitting the orchestration this way keeps applier
    methods pure-write and lets the facade own the cross-cluster choreography.
    """

    def __init__(self, db: Database, *, audit: AuditService) -> None:
        """Bind the applier to a database connection and audit service."""
        self._db = db
        self._audit = audit
        # Protected app.* taxonomy writes route through repositories so each
        # mutation emits a paired audit row (Invariant 10). Repos share this
        # applier's AuditService + connection so their writes participate in
        # the same transaction when composed inside one.
        self._user_categories = UserCategoriesRepo(db, audit=audit)
        self._category_overrides = CategoryOverridesRepo(db, audit=audit)
        self._user_merchants = UserMerchantsRepo(db, audit=audit)
        self._rules = CategorizationRulesRepo(db, audit=audit)
        self._tx_categories = TransactionCategoriesRepo(db, audit=audit)

    @contextmanager
    def _transaction(self) -> Generator[None]:
        """Run the wrapped block inside a DB transaction; rollback on failure.

        Rolls back on BaseException (incl. KeyboardInterrupt/SystemExit) so an
        interrupt mid-write — e.g. between delete_category's cascade DELETEs and
        the final repo delete — can't leave the transaction open. Same pattern as
        BaseRepo._transaction; re-raised immediately, never swallowed.
        """
        self._db.begin()
        try:
            yield
        except BaseException:
            self._db.rollback()
            raise
        else:
            self._db.commit()

    # -- Per-transaction category writes (audit emission) --

    def set_category(
        self,
        transaction_id: str,
        *,
        category: str,
        subcategory: str | None = None,
        categorized_by: Literal["user"] = "user",
        actor: str,
    ) -> None:
        """Upsert a transaction's user category and emit ``category.set`` audit.

        Captures the prior row (or NULL) as ``before`` and the new shape as
        ``after`` so the audit trail can reconstruct overwrites. Mutation +
        audit row commit atomically.
        """
        with self._transaction():
            self.set_category_in_active_txn(
                transaction_id,
                category=category,
                subcategory=subcategory,
                categorized_by=categorized_by,
                actor=actor,
            )

    def set_category_in_active_txn(
        self,
        transaction_id: str,
        *,
        category: str,
        subcategory: str | None,
        categorized_by: Literal["user"] = "user",
        actor: str,
    ) -> None:
        """``set_category`` body without txn boundaries.

        Use when the caller already owns a transaction and wants to batch
        multiple category writes atomically with their own audit chain.

        ``categorized_by`` is restricted to ``"user"``. The user-manual-edit
        path is the only intended use; the direct ``INSERT ... ON CONFLICT``
        below bypasses :meth:`write_categorization`'s precedence guard, so
        admitting a lower-priority source here would let it silently overwrite
        a higher-priority existing categorization. New callers needing a
        non-user write must route through :meth:`write_categorization`.
        """
        category_id = resolve_category_id(self._db, category, subcategory)
        # Routes through the repo (paired audit, full before/after — Req 4).
        # in_outer_txn=True: the caller already owns the transaction.
        self._tx_categories.set(
            transaction_id,
            category=category,
            subcategory=subcategory,
            category_id=category_id,
            categorized_by=categorized_by,
            actor=actor,
            in_outer_txn=True,
        )

    def clear_category(self, transaction_id: str, *, actor: str) -> None:
        """Delete a transaction's category row and emit ``category.clear`` audit.

        Routes through the repo (full before-row capture, Req 4). No-op (and no
        audit event) when no row exists.
        """
        self._tx_categories.clear(transaction_id, actor=actor)

    # -- Merchant management --

    def create_merchant_core(
        self,
        raw_pattern: str | None,
        canonical_name: str,
        *,
        match_type: InternalMatchType = "oneOf",
        category: str | None = None,
        subcategory: str | None = None,
        created_by: str = "ai",
        exemplars: list[str] | None = None,
        actor: str = "system",
    ) -> str:
        """Insert a merchant mapping and return its ``merchant_id``.

        Routes the INSERT through :class:`UserMerchantsRepo` so it emits a
        paired ``app.audit_log`` row (Invariant 10). The facade's
        ``create_merchant`` wraps this with the optional ``reapply``
        post-commit sweep.

        Args:
            raw_pattern: Pattern to match in transaction descriptions; pass
                ``None`` for exemplar-only merchants (``match_type='oneOf'``).
            canonical_name: Clean merchant name for display.
            match_type: How to match: 'exact', 'contains', 'regex', or 'oneOf'.
                Defaults to ``'oneOf'`` — system-created merchants use the
                exemplar accumulator (categorization-matching-mechanics.md
                §Schema changes); user-authored merchants pick 'contains' or
                'regex' explicitly.
            category: Optional default category for this merchant.
            subcategory: Optional default subcategory.
            created_by: Who created the mapping ('user', 'ai', 'rule').
            exemplars: Initial exemplar set (exact match_text values) for
                oneOf merchants. Defaults to ``[]``.
            actor: Audit actor recorded on the ``user_merchant.insert`` event
                (e.g. ``"cli"``, ``"mcp"``); batch-path callers use the
                ``"system"`` default.
        """
        # Resolve the FK alongside the text snapshot (read; stays in the
        # service per Req 2). The repo owns the INSERT + audit.
        category_id = resolve_category_id(self._db, category, subcategory)
        event = self._user_merchants.insert(
            raw_pattern=raw_pattern,
            match_type=match_type,
            canonical_name=canonical_name,
            category=category,
            subcategory=subcategory,
            category_id=category_id,
            created_by=created_by,
            exemplars=exemplars,
            actor=actor,
        )
        merchant_id = event.target_id
        if merchant_id is None:  # pragma: no cover — insert always sets the id
            raise RuntimeError("UserMerchantsRepo.insert returned no merchant_id")
        if exemplars:
            MERCHANT_EXEMPLAR_COUNT.labels(merchant_id=merchant_id).set(len(exemplars))
        logger.info(f"Created user merchant {merchant_id}")
        return merchant_id

    def find_merchant_by_canonical_name(
        self,
        canonical_name: str,
        *,
        category: str,
        subcategory: str | None,
    ) -> str | None:
        """Return ``merchant_id`` for the oneOf merchant with this canonical name + category, or None.

        Used by the exemplar accumulator to detect whether a previously-created
        merchant should grow its exemplar set instead of spawning a duplicate.

        Filters on ``match_type='oneOf'`` because exemplars are only consulted
        for oneOf merchants (see :func:`matcher._match_exemplar`); appending an
        exemplar to a contains/exact/regex merchant is dead data. Also filters
        on ``category``/``subcategory``: two ``oneOf`` merchants can legitimately
        share a canonical name (e.g. an Amazon merchant mapped to ``Shopping``
        and another mapped to ``Groceries``); merging exemplars across them
        would cross-pollinate categorization. When the canonical name collides
        with a different-category merchant, the caller creates a new oneOf
        merchant alongside it — the two coexist, each doing its own job.
        """
        try:
            # IS NOT DISTINCT FROM treats NULL = NULL as true, so both
            # exemplar-set-only merchants (subcategory IS NULL) and ones with
            # a specific subcategory match on a single parameterized query.
            row = self._db.execute(
                f"SELECT merchant_id FROM {USER_MERCHANTS.full_name} "
                "WHERE canonical_name = ? AND match_type = 'oneOf' "
                "AND category = ? AND subcategory IS NOT DISTINCT FROM ? "
                "LIMIT 1",  # noqa: S608  # TableRef constant
                [canonical_name, category, subcategory],
            ).fetchone()
        except duckdb.CatalogException:
            return None
        return row[0] if row else None

    def append_exemplar(self, merchant_id: str, match_text: str) -> int:
        """Append ``match_text`` to a merchant's exemplar set; return new size.

        Routes the UPDATE through :class:`UserMerchantsRepo` so it emits a
        paired audit row (Invariant 10). Idempotent via ``list_distinct``:
        re-appending an existing exemplar leaves the set unchanged and does not
        advance ``updated_at`` (docs/specs/core-updated-at-convention.md). The
        new size comes from the audit event's full after-row, so no extra read
        is needed. Updates the per-merchant gauge to surface any merchant whose
        set is approaching the soft-cap signal (200).
        """
        event = self._user_merchants.append_exemplar(
            merchant_id, match_text, actor="system"
        )
        exemplars = cast("list[str]", (event.after_value or {}).get("exemplars") or [])
        new_size = len(exemplars)
        MERCHANT_EXEMPLAR_COUNT.labels(merchant_id=merchant_id).set(new_size)
        return new_size

    # -- Rule management --

    def create_rules_core(
        self,
        items: Sequence[CategorizationRuleInput],
        *,
        actor: str = "system",
    ) -> RuleCreationResult:
        """Insert categorization rules (idempotent on matcher + output shape).

        Each INSERT routes through :class:`CategorizationRulesRepo` so it emits
        a paired audit row (Invariant 10). The facade's ``create_rules``
        handles the optional ``reapply`` post-commit sweep.

        For each item, looks up an active rule with the same matcher and
        output (``merchant_pattern``, ``match_type``, ``min_amount``,
        ``max_amount``, ``account_id``, ``category``, ``subcategory``);
        ``name`` and ``priority`` are treated as metadata and excluded
        from the dedup key. If found, returns the existing ``rule_id``
        and bumps the ``existing`` counter; otherwise INSERTs a fresh
        12-char UUID hex ``rule_id`` with ``is_active=true`` and
        ``created_by='ai'``.

        Same matcher with a *different* category output is currently
        treated as a new rule, not a conflict — see
        ``docs/specs/moneybin-mcp.md`` "Rule-conflict detection
        (follow-up)" for the deferred conflict-resolution work.

        Per-row insertion failures are caught so a single bad row does
        not abort the batch — they appear in ``error_details``.
        """
        created = 0
        existing = 0
        skipped = 0
        error_details: list[dict[str, str]] = []
        rule_ids: list[str] = []

        for item in items:
            try:
                # DuckDB IS NOT DISTINCT FROM treats NULL = NULL as true,
                # so optional fields (min/max_amount, account_id, subcategory)
                # match on NULL across calls.
                found = self._db.execute(
                    f"""
                    SELECT rule_id FROM {CATEGORIZATION_RULES.full_name}
                    WHERE is_active = true
                      AND merchant_pattern = ?
                      AND match_type = ?
                      AND min_amount IS NOT DISTINCT FROM ?
                      AND max_amount IS NOT DISTINCT FROM ?
                      AND account_id IS NOT DISTINCT FROM ?
                      AND category = ?
                      AND subcategory IS NOT DISTINCT FROM ?
                    LIMIT 1
                    """,  # noqa: S608  # TableRef constant, no user input interpolated
                    [
                        item.merchant_pattern,
                        item.match_type,
                        item.min_amount,
                        item.max_amount,
                        item.account_id,
                        item.category,
                        item.subcategory,
                    ],
                ).fetchone()
                if found is not None:
                    existing += 1
                    rule_ids.append(found[0])
                    continue
                # Phase 1 dual-write: resolve the FK alongside the text snapshot
                # (read; stays in the service per Req 2). `None` is a permitted
                # write — orphaned text is a real state during the dual-write
                # window. Dedup posture is unchanged: text remains the canonical
                # comparator for "same rule" in Phase 1.
                category_id = resolve_category_id(
                    self._db, item.category, item.subcategory
                )
                event = self._rules.insert(
                    name=item.name,
                    merchant_pattern=item.merchant_pattern,
                    match_type=item.match_type,
                    min_amount=item.min_amount,
                    max_amount=item.max_amount,
                    account_id=item.account_id,
                    category=item.category,
                    subcategory=item.subcategory,
                    category_id=category_id,
                    priority=item.priority,
                    created_by="ai",
                    actor=actor,
                )
                rule_id = event.target_id
                if rule_id is None:  # pragma: no cover — insert always sets the id
                    raise RuntimeError("CategorizationRulesRepo.insert returned no id")
                created += 1
                rule_ids.append(rule_id)
            except Exception:  # noqa: BLE001 — DuckDB raises untyped errors on constraint violations
                skipped += 1
                logger.exception(f"create_rules failed for rule {item.name!r}")
                error_details.append({
                    "name": item.name,
                    "reason": "Failed to create rule — check logs for details.",
                })

        return RuleCreationResult(
            created=created,
            existing=existing,
            skipped=skipped,
            error_details=error_details,
            rule_ids=rule_ids,
        )

    def deactivate_rule_core(self, rule_id: str, *, actor: str = "system") -> bool:
        """Soft-delete a rule by setting ``is_active=false``.

        Routes through :class:`CategorizationRulesRepo` so the deactivation
        emits a paired audit row (Invariant 10). Returns ``True`` if the rule
        existed (and is now inactive), ``False`` if no rule with that ID was
        found. The facade's ``deactivate_rule`` handles the optional reapply
        tail (categorization stripping + ``categorize_pending``).
        """
        return self._rules.deactivate(rule_id, actor=actor) is not None

    def delete_rule_categorizations(
        self, rule_id: str, *, actor: str = "system"
    ) -> None:
        """Strip categorizations a now-inactive rule had written.

        Targets only ``categorized_by IN ('rule', 'auto_rule')`` rows with
        this ``rule_id``. Writes from higher-priority sources (user /
        migration / ml / plaid) that happen to reference this rule_id are
        left intact. Run by the facade's ``deactivate_rule`` reapply tail
        immediately before ``categorize_pending`` re-evaluates the affected
        transactions against the remaining active matchers. Routes through the
        repo so each stripped row emits a paired ``category.clear`` audit
        capturing its full prior state (Invariant 10, Req 4). ``actor`` is the
        surface that triggered the deactivation (threaded from ``deactivate_rule``).
        """
        self._tx_categories.delete_by_rule(rule_id, actor=actor)

    # -- Category (taxonomy) management --

    def create_category(
        self,
        category: str,
        *,
        subcategory: str | None = None,
        description: str | None = None,
        actor: str = "system",
    ) -> str:
        """Create a custom user category (active by default).

        Duplicate-text detection scans the full resolved taxonomy in
        ``core.dim_categories`` (seeds ∪ ``app.user_categories``), not just
        ``app.user_categories``, so a user cannot create a row whose
        ``(category, subcategory)`` text collides with a seeded default.
        Permitting such a collision would make ``resolve_category_id`` pick
        between two equally-matching dim rows arbitrarily, binding writer
        FKs to one or the other across calls. V015 relaxed
        ``app.user_categories``'s ``UNIQUE (category, subcategory)``
        constraint — the ``category_id`` PK is now the sole DB-enforced
        uniqueness contract; the cross-source check happens here.

        Raises:
            UserError(code="CATEGORY_ALREADY_EXISTS"): the
                ``(category, subcategory)`` pair is already present in
                ``core.dim_categories`` (either as a seeded default or a
                prior user-created row).
        """
        existing = self._db.execute(
            f"""
            SELECT 1 FROM {CATEGORIES.full_name}
            WHERE category = ? AND subcategory IS NOT DISTINCT FROM ?
            LIMIT 1
            """,  # noqa: S608  # TableRef constant, no user input interpolated
            [category, subcategory],
        ).fetchone()
        if existing:
            sub = f" / {subcategory}" if subcategory else ""
            raise UserError(
                f"Category already exists: {category}{sub}",
                code="CATEGORY_ALREADY_EXISTS",
            )

        # The duplicate check above and the insert below are separate statements
        # (the repo opens its own transaction). MoneyBin's single-writer model
        # (exclusive write lock per database-writer-coordination.md) is what makes
        # this race-free; V015 dropped the UNIQUE(category, subcategory) DB guard,
        # so the lock — not a constraint — is the load-bearing invariant here.
        event = self._user_categories.insert(
            category=category,
            subcategory=subcategory,
            description=description,
            actor=actor,
        )
        if event.target_id is None:  # pragma: no cover — insert always sets the id
            raise RuntimeError("UserCategoriesRepo.insert returned no category_id")
        return event.target_id

    def toggle_category(
        self,
        category_id: str,
        *,
        is_active: bool,
        actor: str = "system",
        in_outer_txn: bool = False,
    ) -> None:
        """Enable or disable a category. Existing categorizations are preserved.

        Default categories (is_default=true) write to ``app.category_overrides``;
        user-created categories update ``app.user_categories.is_active`` directly.
        Both writes route through their repository so each emits a paired audit
        row (Invariant 10).

        Raises:
            UserError(code="CATEGORY_NOT_FOUND"): no category with this ID
                exists in either ``app.user_categories`` or the seeded defaults.
        """
        cat = self._db.execute(
            f"SELECT is_default FROM {CATEGORIES.full_name} WHERE category_id = ?",  # noqa: S608  # TableRef constant
            [category_id],
        ).fetchone()
        if not cat:
            raise UserError(
                f"Category {category_id} not found",
                code="CATEGORY_NOT_FOUND",
            )

        if cat[0]:  # default category — record/upsert the override
            self._category_overrides.set_active(
                category_id, is_active=is_active, actor=actor, in_outer_txn=in_outer_txn
            )
        else:
            self._user_categories.update_active(
                category_id, is_active=is_active, actor=actor, in_outer_txn=in_outer_txn
            )

    def delete_category(
        self, category_id: str, *, force: bool = False, actor: str = "system"
    ) -> None:
        """Hard-delete a user-created category.

        Reference check and cascade both use ``category_id`` FK matching across
        seven tables: ``app.transaction_categories``, ``app.budgets``,
        ``app.user_merchants``, ``app.transaction_splits``,
        ``app.categorization_rules``, ``app.proposed_rules``, and
        ``app.category_source_map``. With ``force=False`` (default) the call
        refuses when any of those tables carries a row with this
        ``category_id``; with ``force=True`` rows in all seven tables are
        deleted before the ``app.user_categories`` row itself is removed.

        Default (seeded) categories cannot be hard-deleted — operators disable
        them via :meth:`toggle_category` so that ``app.category_overrides``
        records the deactivation without destroying the canonical taxonomy row.

        Args:
            category_id: ID of the user-created category to delete.
            force: If True, cascade-delete referencing rows across the seven
                tables above; if False, refuse when references exist.
            actor: Audit actor recorded on the ``user_category.delete`` event
                (e.g. ``"cli"``, ``"mcp"``).

        Raises:
            UserError(code="CATEGORY_NOT_FOUND"): no category with this ID.
            UserError(code="CATEGORY_IS_DEFAULT"): seeded default categories
                cannot be hard-deleted; use ``toggle_category``.
            UserError(code="CATEGORY_HAS_REFERENCES"): force=False and the
                category is referenced by at least one of the seven tracked
                tables.
        """
        existing = self._db.execute(
            f"SELECT 1 FROM {USER_CATEGORIES.full_name} "  # noqa: S608  # TableRef constant
            f"WHERE category_id = ?",
            [category_id],
        ).fetchone()
        if not existing:
            default = self._db.execute(
                f"SELECT 1 FROM {CATEGORIES.full_name} "  # noqa: S608  # TableRef constant
                f"WHERE category_id = ? AND is_default = TRUE",
                [category_id],
            ).fetchone()
            if default:
                raise UserError(
                    f"Default category {category_id} cannot be deleted "
                    f"(use categories_set with is_active=False to disable)",
                    code="CATEGORY_IS_DEFAULT",
                )
            raise UserError(
                f"Category {category_id} not found",
                code="CATEGORY_NOT_FOUND",
            )

        if not force:
            refs_row = self._db.execute(
                f"SELECT "
                f"  EXISTS(SELECT 1 FROM {TRANSACTION_CATEGORIES.full_name} WHERE category_id = ?), "  # noqa: S608  # TableRef constants
                f"  EXISTS(SELECT 1 FROM {BUDGETS.full_name} WHERE category_id = ?), "
                f"  EXISTS(SELECT 1 FROM {USER_MERCHANTS.full_name} WHERE category_id = ?), "
                f"  EXISTS(SELECT 1 FROM {TRANSACTION_SPLITS.full_name} WHERE category_id = ?), "
                f"  EXISTS(SELECT 1 FROM {CATEGORIZATION_RULES.full_name} WHERE category_id = ?), "
                f"  EXISTS(SELECT 1 FROM {PROPOSED_RULES.full_name} WHERE category_id = ?), "
                f"  EXISTS(SELECT 1 FROM {CATEGORY_SOURCE_MAP.full_name} WHERE category_id = ?)",
                [category_id] * 7,
            ).fetchone()
            labels = (
                "transactions",
                "budgets",
                "merchants",
                "splits",
                "rules",
                "proposed rules",
                "source mappings",
            )
            present = [
                label
                for label, flag in zip(labels, refs_row or (), strict=True)
                if flag
            ]
            if present:
                raise UserError(
                    f"Category {category_id} is referenced by "
                    + ", ".join(present)
                    + "; pass force=True to cascade-delete.",
                    code="CATEGORY_HAS_REFERENCES",
                )

        with self._transaction():
            if force:
                # NOTE(Invariant 10): these 7 cascade DELETEs target other
                # protected app.* tables and are still raw. As of Batch B,
                # transaction_categories / user_merchants / categorization_rules
                # / proposed_rules have repos, but budgets and transaction_splits
                # do not (Batch C / AI-PR12). Threading the whole cascade through
                # repos in one pass — when all seven have a delete-by-category_id
                # path — keeps it a single coherent change rather than a
                # half-threaded mix; the lint rule (AI-PR13) lands after that, so
                # nothing forces it earlier.
                for table_const in (
                    TRANSACTION_CATEGORIES,
                    BUDGETS,
                    USER_MERCHANTS,
                    TRANSACTION_SPLITS,
                    CATEGORIZATION_RULES,
                    PROPOSED_RULES,
                    CATEGORY_SOURCE_MAP,
                ):
                    self._db.execute(
                        f"DELETE FROM {table_const.full_name} WHERE category_id = ?",  # noqa: S608  # TableRef constant
                        [category_id],
                    )
            # TODO(Invariant 10 AI-PR12): once budgets + transaction_splits have
            # repos, capture this AuditEvent and thread its audit_id as
            # parent_audit_id into all seven cascade deletes above (routed
            # through their repos).
            self._user_categories.delete(category_id, actor=actor, in_outer_txn=True)

    # -- Guarded categorization write --

    def write_categorization(
        self,
        *,
        transaction_id: str,
        category: str,
        subcategory: str | None,
        categorized_by: str,
        merchant_id: str | None = None,
        rule_id: str | None = None,
        confidence: float | None = None,
        source_type: str = "internal",
        in_outer_txn: bool = False,
    ) -> WriteOutcome:
        """Insert or replace a categorization, respecting source precedence.

        Single guarded write path for ``app.transaction_categories``. Lower
        numeric priority = higher authority (per
        ``categorization-matching-mechanics.md`` §Source precedence). A new
        write succeeds only if its source priority is ≤ the existing row's;
        otherwise the existing row stands and the
        ``CATEGORIZE_WRITE_SKIPPED_PRECEDENCE_TOTAL`` metric is incremented.

        Returns:
            ``WriteOutcome.written=True`` if the write took effect (insert or
            permitted update); ``False`` with ``skipped_reason='lower_priority_source'``
            if a higher-priority categorization already exists.

        Raises:
            ValueError: if ``categorized_by`` is not in :data:`SOURCE_PRIORITY`.
                The generated SQL CASE has no ELSE branch (see
                :func:`priority_case_sql`), so an unknown source would silently
                resolve to NULL priority and never overwrite — fail loudly
                instead of letting a typo masquerade as a precedence skip.
        """
        if categorized_by not in SOURCE_PRIORITY:
            raise ValueError(
                f"Unknown categorized_by={categorized_by!r}; "
                f"must be one of {sorted(SOURCE_PRIORITY)}"
            )
        # FK is paired with text on identical precedence terms. The repo owns
        # the precedence-guarded upsert + paired audit; a precedence-skipped
        # write returns None (no mutation, no audit). Engine writes record their
        # source via categorized_by, so the audit actor is the batch ("system").
        category_id = resolve_category_id(self._db, category, subcategory)
        event = self._tx_categories.upsert_guarded(
            transaction_id,
            category=category,
            subcategory=subcategory,
            category_id=category_id,
            categorized_by=categorized_by,
            merchant_id=merchant_id,
            rule_id=rule_id,
            confidence=confidence,
            source_type=source_type,
            actor="system",
            in_outer_txn=in_outer_txn,
        )
        if event is not None:
            return WriteOutcome(written=True)

        # Row exists with a higher-priority source; record the skip with labels
        # for both sides of the comparison so dashboards can distinguish "ai
        # blocked by user" from "ai blocked by rule" etc.
        existing = self._db.execute(
            f"SELECT categorized_by FROM {TRANSACTION_CATEGORIES.full_name} "
            "WHERE transaction_id = ?",  # noqa: S608  # TRANSACTION_CATEGORIES is a TableRef constant
            [transaction_id],
        ).fetchone()
        CATEGORIZE_WRITE_SKIPPED_PRECEDENCE_TOTAL.labels(
            src_existing=existing[0] if existing else "unknown",
            src_attempted=categorized_by,
        ).inc()
        return WriteOutcome(written=False, skipped_reason="lower_priority_source")
