"""Tests for scripts.generate_reference_docs: the codegen for docs/reference/.

The renderers are exercised on small synthetic inputs so a formatting change
that would desync the checked-in pages is caught by shape, not by a diff of
six thousand generated lines. The drift assertion itself lives in
``tests/test_documentation_policy.py::test_generated_references_are_current``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, cast

import click
import pytest
from pydantic import BaseModel, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from scripts.generate_reference_docs import (
    live_mcp_surface,
    render_cli_pages,
    render_configuration,
    render_mcp_tools,
    stale_pages,
    write_pages,
)


@click.group()
@click.option("--home", type=click.Path(), envvar="TOY_HOME", help="Data directory.")
def toy(home: str | None) -> None:
    """Toy CLI."""


@toy.group()
def db() -> None:
    """Database management."""


@db.command()
@click.argument("backup_path")
@click.option("--passphrase", is_flag=True, help="Derive the key from a passphrase.")
@click.option(
    "-o",
    "--output",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
    help="Output format.",
)
def restore(backup_path: str, passphrase: bool, output: str) -> None:
    """Restore a backup.

    Longer help paragraph.
    """


@db.command(hidden=True)
def secret() -> None:
    """Never advertised."""


@toy.command()
@click.option("--limit", type=click.IntRange(min=1), default=5, show_default=True)
@click.option(
    "--refresh/--no-refresh",
    default=True,
    show_default=True,
    help="Refresh <scope> first; see `moneybin refresh <step>`.",
)
def stats(limit: int, refresh: bool) -> None:
    """Show stats for <scope>."""


@toy.command()
def preview() -> None:
    r"""Preview a file
    before importing it.

    Pass exactly one of:
      --sheet <name>   read one sheet
      --all            read every sheet

    Supported types:
      - CSV
      - Excel

    Examples:
        moneybin preview <path>

        # With a sheet
        moneybin preview a.xlsx --sheet Sheet1

    Or piped:
      cat list.txt \
        | moneybin preview -
    """  # noqa: D205  # the two-line summary is the join case under test


def test_cli_pages_are_one_per_top_level_command_plus_an_index() -> None:
    pages = render_cli_pages(toy)
    assert set(pages) == {"README.md", "db.md", "preview.md", "stats.md"}
    assert pages["README.md"].startswith("<!-- Generated by")
    assert "[`moneybin db`](db.md)" in pages["README.md"]
    assert (
        "| `--home` | path |  | Data directory. Env: `TOY_HOME`. |"
        in pages["README.md"]
    )


def test_cli_page_renders_click_usage_arguments_and_options() -> None:
    page = render_cli_pages(toy)["db.md"]
    assert "# moneybin db" in page
    assert "## moneybin db restore" in page
    assert "Usage: `moneybin db restore [OPTIONS] BACKUP_PATH`" in page
    assert "| `BACKUP_PATH` | text | yes |  |" in page
    assert "| `--passphrase` | flag |  | Derive the key from a passphrase. |" in page
    assert (
        "| `-o, --output` | one of `text`, `json` | `text` | Output format. |" in page
    )
    assert "Longer help paragraph." in page


def test_cli_pages_omit_hidden_commands() -> None:
    page = render_cli_pages(toy)["db.md"]
    assert "secret" not in page


def test_cli_page_renders_numeric_ranges() -> None:
    page = render_cli_pages(toy)["stats.md"]
    assert "| `--limit` | int (≥ 1) | `5` |" in page


def test_cli_page_renders_boolean_pair_defaults_and_escapes_placeholders() -> None:
    """`<scope>` outside a code span is HTML to GitHub; a bool pair has a default."""
    page = render_cli_pages(toy)["stats.md"]
    assert "Show stats for \\<scope>." in page
    assert (
        "| `--refresh / --no-refresh` | flag | `true` | "
        "Refresh \\<scope> first; see `moneybin refresh <step>`. |"
    ) in page


def test_cli_page_fences_indented_help_blocks_and_keeps_lists_as_prose() -> None:
    """`--help` joins the first paragraph and prints later indented lines as is.

    An option table becomes a `text` fence, a transcript a `console` fence
    (consecutive ones merge, and a backslash continuation still counts as a
    transcript line), and an indented list stays prose. Nothing inside a fence
    is escaped.
    """
    page = render_cli_pages(toy)["preview.md"]
    assert (
        "Preview a file before importing it.\n\n"
        "Pass exactly one of:\n\n"
        "```text\n--sheet <name>   read one sheet\n--all            read every sheet\n```\n\n"
        "Supported types:\n  - CSV\n  - Excel\n\n"
        "Examples:\n\n"
        "```console\nmoneybin preview <path>\n\n# With a sheet\n"
        "moneybin preview a.xlsx --sheet Sheet1\n```\n\n"
        "Or piped:\n\n"
        "```console\ncat list.txt \\\n  | moneybin preview -\n```\n\n"
        "Generated from the registered command tree"
    ) in page


def test_stale_pages_reports_orphaned_generated_cli_pages(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A generated page whose command is gone is stale, and write_pages drops it."""
    import scripts.generate_reference_docs as generator

    monkeypatch.setattr(
        generator, "generated_pages", lambda: {Path("cli") / "db.md": "# db\n"}
    )
    cli_dir = tmp_path / "cli"
    cli_dir.mkdir()
    (cli_dir / "db.md").write_text("# db\n")
    (cli_dir / "gone.md").write_text(
        "<!-- Generated by scripts/generate_reference_docs.py from the Typer "
        "command tree. Do not edit; run `make generate-docs` after changing the "
        "source. -->\n"
    )
    (cli_dir / "hand-written.md").write_text("# Kept\n")
    assert stale_pages(tmp_path) == [Path("cli") / "gone.md"]
    assert write_pages(tmp_path) == [Path("cli") / "gone.md"]
    assert sorted(p.name for p in cli_dir.iterdir()) == ["db.md", "hand-written.md"]


SURFACE: dict[str, Any] = {
    "tool_count": 2,
    "tools": [
        {
            "name": "zeta",
            "definition": {
                "description": "Second sentence first. Then more.",
                "annotations": {"readOnlyHint": False, "destructiveHint": True},
                "inputSchema": {"properties": {}, "type": "object"},
            },
        },
        {
            "name": "accounts",
            "definition": {
                "description": "List accounts.",
                "annotations": {"readOnlyHint": True, "idempotentHint": True},
                "inputSchema": {
                    "properties": {
                        "limit": {"type": "integer", "default": 100, "minimum": 1},
                        "view": {
                            "type": "string",
                            "enum": ["list", "detail"],
                            "default": "list",
                        },
                        "query": {
                            "anyOf": [{"type": "string"}, {"type": "null"}],
                            "default": None,
                        },
                    },
                    "required": ["view"],
                    "type": "object",
                },
            },
        },
    ],
}


def test_mcp_page_sorts_tools_and_renders_schema_rows() -> None:
    page = render_mcp_tools(SURFACE, {"accounts": "critical", "zeta": "low"})
    assert page.index("### accounts") < page.index("### zeta")
    assert "The standard registry exposes 2 tools." in page
    assert (
        "| [`zeta`](#zeta) | Second sentence first. | write, destructive, not idempotent | `low` |"
        in page
    )
    assert "| `limit` | integer | `100` | ≥ 1 |" in page
    assert "| `view` | one of `list`, `detail` | `list` | required |" in page
    assert "| `query` | string |  |  |" in page
    assert "No parameters." in page


def test_mcp_page_refuses_a_tool_without_a_registered_sensitivity() -> None:
    with pytest.raises(ValueError, match="zeta"):
        render_mcp_tools(SURFACE, {"accounts": "critical"})


def test_live_mcp_surface_lists_every_tool_with_a_registered_tier() -> None:
    """One in-process boot, no database: what a client sees, plus each tier.

    The page renders from this rather than from the frozen snapshot, so a tool
    description edited without regenerating fails the unit drift test instead
    of only the integration snapshot check.
    """
    surface, sensitivities = live_mcp_surface()
    tools = cast(list[dict[str, object]], surface["tools"])
    assert tools
    assert surface["tool_count"] == len(tools)
    assert {str(tool["name"]) for tool in tools} <= set(sensitivities)


class Nested(BaseModel):
    """A nested settings section."""

    limit: int = Field(default=10, ge=1, description="Row cap.")
    token: SecretStr | None = Field(default=None, description="API token.")


class ToySettings(BaseSettings):
    """A settings root with a scalar, an aliased section, and a home-relative path."""

    model_config = SettingsConfigDict(env_prefix="MONEYBIN_", env_nested_delimiter="__")

    debug: bool = Field(default=False, description="Enable debug mode.")
    import_: Nested = Field(default_factory=Nested, alias="import")
    inbox: Path = Field(
        default_factory=lambda: Path.home() / "Documents", description="Inbox root."
    )
    logging: Nested = Field(default_factory=Nested, description="Log settings.")


def test_configuration_page_marks_the_sections_the_profile_passes_whole() -> None:
    """`database`, `data`, and `logging` come from the profile, not the environment."""
    page = render_configuration(ToySettings)
    note = "so the variables below are not read today"
    assert page.count(note) == 1
    assert page.index("## logging") < page.index(note)
    assert "profile set" not in page


def test_configuration_page_derives_env_names_from_field_names() -> None:
    page = render_configuration(ToySettings)
    assert "| `MONEYBIN_DEBUG` | bool | `false` | Enable debug mode. |" in page
    assert "## import" in page
    assert "| `MONEYBIN_IMPORT___LIMIT` | int (≥ 1) | `10` | Row cap. |" in page
    assert (
        "| `MONEYBIN_IMPORT___TOKEN` | secret (optional) | unset | API token. |" in page
    )


def test_configuration_page_relativizes_home_and_never_prints_secrets() -> None:
    page = render_configuration(ToySettings)
    assert "| `MONEYBIN_INBOX` | Path | `~/Documents` | Inbox root. |" in page
    assert str(Path.home()) not in page


def test_configuration_page_refuses_an_undescribed_field() -> None:
    class Bare(BaseSettings):
        model_config = SettingsConfigDict(env_prefix="MONEYBIN_")
        debug: bool = False

    with pytest.raises(ValueError, match="MONEYBIN_DEBUG"):
        render_configuration(Bare)
