"""Tests for scripts.generate_reference_docs: the codegen for docs/reference/.

The renderers are exercised on small synthetic inputs so a formatting change
that would desync the checked-in pages is caught by shape, not by a diff of
six thousand generated lines. The drift assertion itself lives in
``tests/test_documentation_policy.py::test_generated_references_are_current``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, cast

import click
import pytest
from pydantic import BaseModel, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from scripts.generate_reference_docs import (
    live_mcp_surface,
    render_cli_pages,
    render_configuration,
    render_mcp_tools,
    stale_pages,
    write_pages,
)


@click.group()
@click.option("--home", type=click.Path(), envvar="TOY_HOME", help="Data directory.")
def toy(home: str | None) -> None:
    """Toy CLI."""


@toy.group()
def db() -> None:
    """Database management."""


@db.command()
@click.argument("backup_path")
@click.option("--passphrase", is_flag=True, help="Derive the key from a passphrase.")
@click.option(
    "-o",
    "--output",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
    help="Output format.",
)
def restore(backup_path: str, passphrase: bool, output: str) -> None:
    """Restore a backup.

    Longer help paragraph.
    """


@db.command(hidden=True)
def secret() -> None:
    """Never advertised."""


@toy.command()
@click.option("--limit", type=click.IntRange(min=1), default=5, show_default=True)
@click.option(
    "--refresh/--no-refresh",
    default=True,
    show_default=True,
    help="Refresh <scope> first; see `moneybin refresh <step>`.",
)
def stats(limit: int, refresh: bool) -> None:
    """Show stats for <scope>."""


@toy.command()
def preview() -> None:
    r"""Preview a file
    before importing it.

    Pass exactly one of:
      --sheet <name>   read one sheet
      --all            read every sheet

    Supported types:
      - CSV
      - Excel

    Examples:
        moneybin preview <path>

        # With a sheet
        moneybin preview a.xlsx --sheet Sheet1

    Or piped:
      cat list.txt \
        | moneybin preview -
    """  # noqa: D205  # the two-line summary is the join case under test


def test_cli_pages_are_one_per_top_level_command_plus_an_index() -> None:
    pages = render_cli_pages(toy)
    assert set(pages) == {"README.md", "db.md", "preview.md", "stats.md"}
    assert pages["README.md"].startswith("<!-- Generated by")
    assert "[`moneybin db`](db.md)" in pages["README.md"]
    assert (
        "| `--home` | path |  | Data directory. Env: `TOY_HOME`. |"
        in pages["README.md"]
    )


def test_cli_page_renders_click_usage_arguments_and_options() -> None:
    page = render_cli_pages(toy)["db.md"]
    assert "# moneybin db" in page
    assert "## moneybin db restore" in page
    assert "Usage: `moneybin db restore [OPTIONS] BACKUP_PATH`" in page
    assert "| `BACKUP_PATH` | text | yes |  |" in page
    assert "| `--passphrase` | flag |  | Derive the key from a passphrase. |" in page
    assert (
        "| `-o, --output` | one of `text`, `json` | `text` | Output format. |" in page
    )
    assert "Longer help paragraph." in page


def test_cli_pages_omit_hidden_commands() -> None:
    page = render_cli_pages(toy)["db.md"]
    assert "secret" not in page


def test_cli_page_renders_numeric_ranges() -> None:
    page = render_cli_pages(toy)["stats.md"]
    assert "| `--limit` | int (≥ 1) | `5` |" in page


def test_cli_page_renders_boolean_pair_defaults_and_escapes_placeholders() -> None:
    """`<scope>` outside a code span is HTML to GitHub; a bool pair has a default."""
    page = render_cli_pages(toy)["stats.md"]
    assert "Show stats for \\<scope>." in page
    assert (
        "| `--refresh / --no-refresh` | flag | `true` | "
        "Refresh \\<scope> first; see `moneybin refresh <step>`. |"
    ) in page


def test_cli_page_fences_indented_help_blocks_and_keeps_lists_as_prose() -> None:
    """`--help` joins the first paragraph and prints later indented lines as is.

    An option table becomes a `text` fence, a transcript a `console` fence
    (consecutive ones merge, and a backslash continuation still counts as a
    transcript line), and an indented list stays prose. Nothing inside a fence
    is escaped.
    """
    page = render_cli_pages(toy)["preview.md"]
    assert (
        "Preview a file before importing it.\n\n"
        "Pass exactly one of:\n\n"
        "```text\n--sheet <name>   read one sheet\n--all            read every sheet\n```\n\n"
        "Supported types:\n  - CSV\n  - Excel\n\n"
        "Examples:\n\n"
        "```console\nmoneybin preview <path>\n\n# With a sheet\n"
        "moneybin preview a.xlsx --sheet Sheet1\n```\n\n"
        "Or piped:\n\n"
        "```console\ncat list.txt \\\n  | moneybin preview -\n```\n\n"
        "Generated from the registered command tree"
    ) in page


def test_stale_pages_reports_orphaned_generated_cli_pages(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A generated page whose command is gone is stale, and write_pages drops it."""
    import scripts.generate_reference_docs as generator

    monkeypatch.setattr(
        generator, "generated_pages", lambda: {Path("cli") / "db.md": "# db\n"}
    )
    cli_dir = tmp_path / "cli"
    cli_dir.mkdir()
    (cli_dir / "db.md").write_text("# db\n")
    (cli_dir / "gone.md").write_text(
        "<!-- Generated by scripts/generate_reference_docs.py from the Typer "
        "command tree. Do not edit; run `make generate-docs` after changing the "
        "source. -->\n"
    )
    (cli_dir / "hand-written.md").write_text("# Kept\n")
    assert stale_pages(tmp_path) == [Path("cli") / "gone.md"]
    assert write_pages(tmp_path) == [Path("cli") / "gone.md"]
    assert sorted(p.name for p in cli_dir.iterdir()) == ["db.md", "hand-written.md"]


SURFACE: dict[str, Any] = {
    "tool_count": 2,
    "tools": [
        {
            "name": "zeta",
            "definition": {
                "description": "Second sentence first. Then more.",
                "annotations": {"readOnlyHint": False, "destructiveHint": True},
                "inputSchema": {"properties": {}, "type": "object"},
            },
        },
        {
            "name": "accounts",
            "definition": {
                "description": "List accounts.",
                "annotations": {"readOnlyHint": True, "idempotentHint": True},
                "inputSchema": {
                    "properties": {
                        "limit": {"type": "integer", "default": 100, "minimum": 1},
                        "view": {
                            "type": "string",
                            "enum": ["list", "detail"],
                            "default": "list",
                        },
                        "query": {
                            "anyOf": [{"type": "string"}, {"type": "null"}],
                            "default": None,
                        },
                        "scope": {
                            "anyOf": [
                                {
                                    "oneOf": [
                                        {
                                            "description": "Every thing.",
                                            "properties": {
                                                "kind": {
                                                    "const": "everything",
                                                    "type": "string",
                                                }
                                            },
                                            "required": ["kind"],
                                            "type": "object",
                                        },
                                        {
                                            "description": "One thing.",
                                            "properties": {
                                                "kind": {
                                                    "const": "one",
                                                    "type": "string",
                                                },
                                                "thing_id": {"type": "string"},
                                            },
                                            "required": ["kind", "thing_id"],
                                            "type": "object",
                                        },
                                    ]
                                },
                                {"type": "null"},
                            ],
                            "default": None,
                        },
                        "target": {
                            "oneOf": [
                                {
                                    "description": "A widget target.",
                                    "properties": {
                                        "kind": {"const": "widget", "type": "string"},
                                        "widget_id": {"type": "string"},
                                    },
                                    "required": ["kind", "widget_id"],
                                    "type": "object",
                                },
                                {
                                    "description": "A gadget target.",
                                    "properties": {
                                        "kind": {"const": "gadget", "type": "string"},
                                        "gadget_id": {"type": "string"},
                                    },
                                    "required": ["kind", "gadget_id"],
                                    "type": "object",
                                },
                            ]
                        },
                        "requests": {
                            "items": {
                                "oneOf": [
                                    {
                                        "description": "Add a thing.",
                                        "properties": {
                                            "kind": {
                                                "const": "thing_add",
                                                "type": "string",
                                            },
                                            "name": {"type": "string"},
                                        },
                                        "required": ["kind", "name"],
                                        "type": "object",
                                    },
                                    {
                                        "description": "Remove a thing.",
                                        "properties": {
                                            "kind": {
                                                "const": "thing_remove",
                                                "type": "string",
                                            },
                                            "name": {"type": "string"},
                                        },
                                        "required": ["kind", "name"],
                                        "type": "object",
                                    },
                                ]
                            },
                            "type": "array",
                        },
                    },
                    "required": ["view"],
                    "type": "object",
                },
            },
        },
    ],
}


def test_mcp_page_sorts_tools_and_renders_schema_rows() -> None:
    page = render_mcp_tools(SURFACE, {"accounts": "critical", "zeta": "low"})
    assert page.index("### accounts") < page.index("### zeta")
    assert "The standard registry exposes 2 tools." in page
    assert (
        "| [`zeta`](#zeta) | Second sentence first. | write, destructive, not idempotent | `low` |"
        in page
    )
    assert "| `limit` | integer | `100` | ≥ 1 |" in page
    assert "| `view` | one of `list`, `detail` | `list` | required |" in page
    assert "| `query` | string |  |  |" in page
    assert "No parameters." in page


def test_mcp_page_renders_oneof_variants_by_discriminator() -> None:
    """A ``oneOf`` parameter names each variant and lists its fields below."""
    page = render_mcp_tools(SURFACE, {"accounts": "critical", "zeta": "low"})
    assert "| `target` | one of `widget`, `gadget` |  |  |" in page
    assert "| `requests` | array of one of `thing_add`, `thing_remove` |  |  |" in page
    assert "#### Variants of `target`" in page
    assert "##### `widget`" in page
    assert "A widget target." in page
    assert "| `widget_id` | string |  | required |" in page
    assert "##### `gadget`" in page
    assert "A gadget target." in page
    assert "| `gadget_id` | string |  | required |" in page
    assert "#### Variants of `requests`" in page
    assert "##### `thing_add`" in page
    assert "Add a thing." in page
    assert "##### `thing_remove`" in page
    assert "Remove a thing." in page
    assert (
        page.index("### accounts")
        < page.index("| `target` |")
        < page.index("#### Variants of `target`")
        < page.index("#### Variants of `requests`")
        < page.index("### zeta")
    )


def test_mcp_page_renders_variants_of_a_nullable_oneof() -> None:
    """An optional discriminated union gets the same variants block as a required one."""
    page = render_mcp_tools(SURFACE, {"accounts": "critical", "zeta": "low"})
    assert "| `scope` | one of `everything`, `one` |" in page
    assert "#### Variants of `scope`" in page
    assert "##### `everything`" in page
    assert "Every thing." in page
    assert "##### `one`" in page
    assert "One thing." in page
    assert "| `thing_id` | string |  | required |" in page
    assert page.index("#### Variants of `scope`") < page.index("### zeta")


def test_mcp_page_names_oneof_variant_by_title_without_a_const() -> None:
    """A variant with no ``const``-bearing property falls back to its ``title``."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "titled",
                "definition": {
                    "description": "Has titled variants.",
                    "annotations": {"readOnlyHint": True},
                    "inputSchema": {
                        "properties": {
                            "target": {
                                "oneOf": [
                                    {
                                        "title": "Widget Variant",
                                        "description": "A widget target.",
                                        "properties": {"widget_id": {"type": "string"}},
                                        "required": ["widget_id"],
                                        "type": "object",
                                    },
                                    {
                                        "title": "Gadget Variant",
                                        "description": "A gadget target.",
                                        "properties": {"gadget_id": {"type": "string"}},
                                        "required": ["gadget_id"],
                                        "type": "object",
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"titled": "low"})
    assert "| `target` | one of `Widget Variant`, `Gadget Variant` |  |  |" in page
    assert "##### `Widget Variant`" in page
    assert "##### `Gadget Variant`" in page


def test_mcp_page_names_oneof_variant_by_position_without_a_title() -> None:
    """A variant with neither ``const`` nor ``title`` falls back to its position."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "untitled",
                "definition": {
                    "description": "Has untitled variants.",
                    "annotations": {"readOnlyHint": True},
                    "inputSchema": {
                        "properties": {
                            "target": {
                                "oneOf": [
                                    {
                                        "description": "First option.",
                                        "properties": {"value": {"type": "string"}},
                                        "required": ["value"],
                                        "type": "object",
                                    },
                                    {
                                        "description": "Second option.",
                                        "properties": {"value": {"type": "string"}},
                                        "required": ["value"],
                                        "type": "object",
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"untitled": "low"})
    assert "| `target` | one of `variant 1`, `variant 2` |  |  |" in page
    assert "##### `variant 1`" in page
    assert "##### `variant 2`" in page


def test_mcp_page_renders_conditional_required_and_else_forbidden() -> None:
    """A ``state``-conditioned field states when it is required, and ``else`` forbidden."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "widget_target_set",
                "definition": {
                    "description": "Set one widget target.",
                    "annotations": {"readOnlyHint": False},
                    "inputSchema": {
                        "properties": {
                            "target": {
                                "oneOf": [
                                    {
                                        "description": "A local target.",
                                        "properties": {
                                            "kind": {
                                                "const": "local",
                                                "type": "string",
                                            },
                                            "state": {"type": "string"},
                                            "local_path": {
                                                "type": "string",
                                                "minLength": 1,
                                            },
                                        },
                                        "required": ["kind", "state"],
                                        "type": "object",
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "state": {"const": "present"}
                                                    },
                                                    "required": ["state"],
                                                },
                                                "then": {
                                                    "required": ["local_path"],
                                                    "properties": {
                                                        "local_path": {
                                                            "not": {"type": "null"}
                                                        }
                                                    },
                                                },
                                                "else": {
                                                    "not": {
                                                        "anyOf": [
                                                            {"required": ["local_path"]}
                                                        ]
                                                    }
                                                },
                                            }
                                        ],
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"widget_target_set": "low"})
    assert (
        "| `local_path` | string |  | min length 1; required when `state` is "
        "`present`; forbidden unless `state` is `present` |" in page
    )


def test_mcp_page_merges_conditional_forbidden_clauses_across_branches() -> None:
    """Two branches forbidding the same field on the same discriminator merge with ``or``."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "taxonomy_set",
                "definition": {
                    "description": "Set one taxonomy target.",
                    "annotations": {"readOnlyHint": False},
                    "inputSchema": {
                        "properties": {
                            "items": {
                                "oneOf": [
                                    {
                                        "description": "A category target.",
                                        "properties": {
                                            "kind": {
                                                "const": "category",
                                                "type": "string",
                                            },
                                            "state": {"type": "string"},
                                            "category": {"type": "string"},
                                        },
                                        "required": ["kind", "state"],
                                        "type": "object",
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "state": {"const": "present"}
                                                    },
                                                    "required": ["state"],
                                                },
                                                "then": {"required": ["category"]},
                                            },
                                            {
                                                "if": {
                                                    "properties": {
                                                        "state": {"const": "inactive"}
                                                    },
                                                    "required": ["state"],
                                                },
                                                "then": {
                                                    "not": {
                                                        "anyOf": [
                                                            {"required": ["category"]}
                                                        ]
                                                    }
                                                },
                                            },
                                            {
                                                "if": {
                                                    "properties": {
                                                        "state": {"const": "absent"}
                                                    },
                                                    "required": ["state"],
                                                },
                                                "then": {
                                                    "not": {
                                                        "anyOf": [
                                                            {"required": ["category"]}
                                                        ]
                                                    }
                                                },
                                            },
                                        ],
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"taxonomy_set": "low"})
    assert (
        "| `category` | string |  | required when `state` is `present`; "
        "forbidden when `state` is `inactive` or `absent` |" in page
    )


def test_mcp_page_renders_conditional_must_be_const() -> None:
    """A discriminator branch that fixes a field's value states it as ``must be``."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "reviews_decide",
                "definition": {
                    "description": "Decide one review proposal.",
                    "annotations": {"readOnlyHint": False},
                    "inputSchema": {
                        "properties": {
                            "decisions": {
                                "oneOf": [
                                    {
                                        "description": "An auto-rule decision.",
                                        "properties": {
                                            "kind": {
                                                "const": "auto_rule",
                                                "type": "string",
                                            },
                                            "decision": {"type": "string"},
                                            "allow_broad": {"type": "boolean"},
                                        },
                                        "required": ["kind", "decision"],
                                        "type": "object",
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "decision": {"const": "reject"}
                                                    },
                                                    "required": ["decision"],
                                                },
                                                "then": {
                                                    "properties": {
                                                        "allow_broad": {"const": False}
                                                    }
                                                },
                                            },
                                        ],
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"reviews_decide": "low"})
    assert (
        "| `allow_broad` | boolean |  | must be `false` when `decision` is "
        "`reject` |" in page
    )


def test_mcp_page_renders_a_conditional_keyed_on_another_field_being_set() -> None:
    """An ``if`` testing presence rather than a constant renders as "is set".

    The category/subcategory rule is shaped this way — a subcategory is only
    meaningful under a parent — so the condition is "the other field was
    supplied", which no ``const`` can express.
    """
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "widget_label_set",
                "definition": {
                    "description": "Label one widget.",
                    "annotations": {"readOnlyHint": False},
                    "inputSchema": {
                        "properties": {
                            "target": {
                                "oneOf": [
                                    {
                                        "description": "A labelled target.",
                                        "properties": {
                                            "kind": {
                                                "const": "label",
                                                "type": "string",
                                            },
                                            "category": {"type": "string"},
                                            "subcategory": {"type": "string"},
                                        },
                                        "required": ["kind"],
                                        "type": "object",
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "subcategory": {
                                                            "not": {"type": "null"}
                                                        }
                                                    },
                                                    "required": ["subcategory"],
                                                },
                                                "then": {
                                                    "required": ["category"],
                                                    "properties": {
                                                        "category": {
                                                            "not": {"type": "null"}
                                                        }
                                                    },
                                                },
                                            }
                                        ],
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    page = render_mcp_tools(surface, {"widget_label_set": "low"})
    assert "| `category` | string |  | required when `subcategory` is set |" in page


def test_mcp_page_conditional_tripwire_raises_on_unrecognized_if() -> None:
    """An ``if`` outside the closed vocabulary fails loudly, naming param and variant."""
    surface: dict[str, Any] = {
        "tool_count": 1,
        "tools": [
            {
                "name": "widget_set",
                "definition": {
                    "description": "Set one widget.",
                    "annotations": {"readOnlyHint": False},
                    "inputSchema": {
                        "properties": {
                            "target": {
                                "oneOf": [
                                    {
                                        "description": "A weird target.",
                                        "properties": {
                                            "kind": {
                                                "const": "weird",
                                                "type": "string",
                                            },
                                            "a": {"type": "string"},
                                            "b": {"type": "string"},
                                        },
                                        "required": ["kind"],
                                        "type": "object",
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "a": {"const": "x"},
                                                        "b": {"const": "y"},
                                                    },
                                                    "required": ["a", "b"],
                                                },
                                                "then": {"required": ["a"]},
                                            },
                                        ],
                                    },
                                ]
                            },
                        },
                        "type": "object",
                    },
                },
            },
        ],
    }
    with pytest.raises(ValueError) as exc_info:
        render_mcp_tools(surface, {"widget_set": "low"})
    assert "target" in str(exc_info.value)
    assert "weird" in str(exc_info.value)


def test_mcp_page_refuses_a_tool_without_a_registered_sensitivity() -> None:
    with pytest.raises(ValueError, match="zeta"):
        render_mcp_tools(SURFACE, {"accounts": "critical"})


def test_live_mcp_surface_lists_every_tool_with_a_registered_tier() -> None:
    """One in-process boot, no database: what a client sees, plus each tier.

    The page renders from this rather than from the frozen snapshot, so a tool
    description edited without regenerating fails the unit drift test instead
    of only the integration snapshot check.
    """
    surface, sensitivities = live_mcp_surface()
    tools = cast(list[dict[str, object]], surface["tools"])
    assert tools
    assert surface["tool_count"] == len(tools)
    assert {str(tool["name"]) for tool in tools} <= set(sensitivities)


class Nested(BaseModel):
    """A nested settings section."""

    limit: int = Field(default=10, ge=1, description="Row cap.")
    token: SecretStr | None = Field(default=None, description="API token.")


class ToySettings(BaseSettings):
    """A settings root with a scalar, an aliased section, and a home-relative path."""

    model_config = SettingsConfigDict(env_prefix="MONEYBIN_", env_nested_delimiter="__")

    debug: bool = Field(default=False, description="Enable debug mode.")
    import_: Nested = Field(default_factory=Nested, alias="import")
    inbox: Path = Field(
        default_factory=lambda: Path.home() / "Documents", description="Inbox root."
    )
    logging: Nested = Field(default_factory=Nested, description="Log settings.")


def test_configuration_page_marks_the_sections_the_profile_passes_whole() -> None:
    """`database`, `data`, and `logging` come from the profile, not the environment."""
    page = render_configuration(ToySettings)
    note = "so the variables below are not read today"
    assert page.count(note) == 1
    assert page.index("## logging") < page.index(note)
    assert "profile set" not in page


def test_configuration_page_derives_env_names_from_field_names() -> None:
    page = render_configuration(ToySettings)
    assert "| `MONEYBIN_DEBUG` | bool | `false` | Enable debug mode. |" in page
    assert "## import" in page
    assert "| `MONEYBIN_IMPORT___LIMIT` | int (≥ 1) | `10` | Row cap. |" in page
    assert (
        "| `MONEYBIN_IMPORT___TOKEN` | secret (optional) | unset | API token. |" in page
    )


def test_configuration_page_relativizes_home_and_never_prints_secrets() -> None:
    page = render_configuration(ToySettings)
    assert "| `MONEYBIN_INBOX` | Path | `~/Documents` | Inbox root. |" in page
    assert str(Path.home()) not in page


def test_configuration_page_refuses_an_undescribed_field() -> None:
    class Bare(BaseSettings):
        model_config = SettingsConfigDict(env_prefix="MONEYBIN_")
        debug: bool = False

    with pytest.raises(ValueError, match="MONEYBIN_DEBUG"):
        render_configuration(Bare)
